# Load libraries
library(tidyverse)
library(Hmisc)
library(broom)
library(qgcomp)
library(rjags)
library(LUCIDus)
library(plotly)
library(gWQS)
library(flextable)
library(magrittr)
library(summarytools)
# install.packages("bkmr")
library(bkmr)
