---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```

## Checking SNPs
**x14_94378610, x17_66214462, x19_19268740 were excluded from analysis**
```{r correlation of SNPs}

pfc_chem_summaries <-  data_hcc %>%
  dplyr::select(x1_220796686:x22_43928850) %>%
  pivot_longer(cols = x1_220796686:x22_43928850) %>% 
  group_by(name) %>% 
  summarise(pctna   = mean(value == 0, na.rm = TRUE), 
            variance = var(value, na.rm = TRUE),
            mean    = mean(value, na.rm = TRUE))


snp_name_df <- pfc_chem_summaries %>% 
  filter(pctna < 0.75) %>% dplyr::select(name)

snp_name_scld <- paste0(snp_name_df$name, "_scld")
```

## summary of SNPs
```{r summary of SNPs}
summarytools::view(summarytools::dfSummary(data_hcc%>% 
                                             dplyr::select(snp_name_df$name),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")
```

## summary of SNPs after normalized
```{r summary of SNPs after normalized}
data_analysis_hcc_snp <- data_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_snp <- data_nafld_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_snp <- data_other_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_hcc_japan_snp <- data_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_japan_snp <- data_nafld_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_japan_snp <- data_other_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 
  
data_analysis_hcc_latino_snp <- data_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_latino_snp <- data_nafld_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_latino_snp <- data_other_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

summarytools::view(summarytools::dfSummary(data_analysis_hcc_japan_snp%>%
                                             dplyr::select(contains("scld"), -contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")


summarytools::view(summarytools::dfSummary(data_analysis_hcc_latino_snp%>%
                                             dplyr::select(contains("scld"),
                                                           -contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")

summarytools::view(summarytools::dfSummary(data_analysis_hcc_snp%>%
                                             dplyr::select(contains("scld"),
                                                           -contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")

```

