---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) { 
      out_dir <- 'html_reports';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, '0_2 Interaction between SNPs and PFAS.html')) })
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)


source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```

## Checking SNPs
**x14_94378610, x17_66214462, x19_19268740 were excluded from analysis**
```{r correlation of SNPs}
pfc_chem_summaries <-  data_hcc %>%
  dplyr::select(x1_220796686:x22_43928850) %>%
  pivot_longer(cols = x1_220796686:x22_43928850) %>% 
  group_by(name) %>% 
  summarise(pctna   = mean(value == 0, na.rm = TRUE), 
            variance = var(value, na.rm = TRUE),
            mean    = mean(value, na.rm = TRUE))

snp_name_df <-  tidylog::left_join(pfc_chem_summaries, 
                                   snp_info, by = c("name" = "snp_name")) |>
  filter(pctna < 0.75) %>% dplyr::select(name)

snp_name_scld <- c(paste0(snp_name_df$name, "_scld"))

```

## summary of SNPs
```{r summary of SNPs}
summarytools::view(
  summarytools::dfSummary(data_hcc %>% 
                            dplyr::select(snp_name_df$name),
                          style = 'grid',
                          max.distinct.values = 10, 
                          plain.ascii =   FALSE, 
                          valid.col = FALSE, 
                          headings = FALSE), method = "render")
```

## summary of SNPs after normalized
```{r summary of SNPs after normalized}
data_analysis_hcc_snp <- data_hcc %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_snp <- data_nafld_hcc %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_snp <- data_other_hcc %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_hcc_japan_snp <- data_hcc %>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_japan_snp <- data_nafld_hcc %>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_japan_snp <- data_other_hcc %>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_hcc_latino_snp <- data_hcc %>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_latino_snp <- data_nafld_hcc %>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_latino_snp <- data_other_hcc %>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

summarytools::view(summarytools::dfSummary(data_analysis_hcc_japan_snp%>%
                                             dplyr::select(contains("scld"), -contains("pfas")),
                                           style = 'grid',
                                           max.distinct.values = 10, 
                                           plain.ascii =   FALSE, 
                                           valid.col = FALSE, 
                                           headings = FALSE), method = "render")


summarytools::view(summarytools::dfSummary(data_analysis_hcc_latino_snp%>%
                                             dplyr::select(contains("scld"),
                                                           -contains("pfas")),
                                           style = 'grid',
                                           max.distinct.values = 10, 
                                           plain.ascii =   FALSE, 
                                           valid.col = FALSE, 
                                           headings = FALSE), method = "render")

summarytools::view(summarytools::dfSummary(data_analysis_hcc_snp%>%
                                             dplyr::select(contains("scld"),
                                                           -contains("pfas")),
                                           style = 'grid',
                                           max.distinct.values = 10, 
                                           plain.ascii =   FALSE, 
                                           valid.col = FALSE, 
                                           headings = FALSE), method = "render")

```

## Analysis 1: PRS risk score
```{r }
hist(log(data_hcc$prs_wt))
as.numeric(gtools::quantcut(data_hcc$prs_wt, q = 10))
# mainmod <- clogit(status ~ pfas_lg2_PFHpA*scale(prs_wt) +
x = as.numeric()

for(i in 2:20) {
  mainmod1 <- clogit(status ~ pfas_lg2_PFHpA + (gtools::quantcut(data_hcc$prs_wt, q = i)) +
                       v1 + v2 + v3 + v4 + v5 + v6 + 
                       alcohol_intake +
                       smokestatus +
                       q1_dp_amds_totscore +
                       q1_fdgp7 +
                       strata(setnum), 
                     data = data_hcc) 
  
  mainmod2 <- clogit(status ~ pfas_lg2_PFHpA*(gtools::quantcut(data_hcc$prs_wt, q = i)) +
                       v1 + v2 + v3 + v4 + v5 + v6 + 
                       alcohol_intake +
                       smokestatus +
                       q1_dp_amds_totscore +
                       q1_fdgp7 +
                       strata(setnum), 
                     data = data_hcc) 
  x[i] = tidy(anova(mainmod1, mainmod2))$p.value[2]
  # tidy(mainmod)
  # x[i] = tidy(mainmod)$p.value[nrow(tidy(mainmod))]
}

min(x, na.rm = TRUE)

data_hcc |> select(contains("prs")) |> colnames()
# "prs_uw"         "prs_wt"         "prs_uw_cat"     "prs_wt_cat"     "prs_uw_median"  "prs_wt_median"  "prs_uw_tertile"
```


# Analysis 2: Individual SNPS
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
# 1. Set Covariates ----
# Covariates for main exposure outcome associations
covariate_input <- " alcohol_intake + smokestatus + q1_dp_amds_totscore + 
q1_fdgp7"


# This was the original model before correcting the covariates
# covariate_input <- " bmi +  smokestatus + alcohol_intake + diabetes"

# create dataframe with names of dependent vars (PFAS) 
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
snp_name <- tibble(snp = snp_name_scld)

pfas_snp <- expand_grid(pfas_names, snp_name) %>%
  mutate(pfas_snp = paste(exposure,"*",snp)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# 2. Make all clogit formulas ----

ind_vars <- expand_grid(pfas_snp,covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6",
                         "+", pfas_snp,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 


ind_vars$clogit_out1 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_japan_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 


ind_vars$clogit_out2 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_latino_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  dplyr::select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>% 
  unnest(clogit_out1) %>% 
  dplyr::select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))



all_results_df_hcc_latino <- ind_vars %>% 
  unnest(clogit_out2) %>% 
  dplyr::select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  dplyr::select(exposure, snp, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |> 
  mutate(
    effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                            str_detect(term, "^x")   ~ "Genetic Risk",
                            TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc3 <- all_results_df_hcc2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup() %>%
  tidylog::left_join(snp_info%>%
                       dplyr::select(rsid, snp_name, genes), by = c("snp"="snp_name"))

### Japanese American
all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  dplyr::select(exposure, snp,term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |> 
  mutate(
    effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                            str_detect(term, "^x")   ~ "Genetic Risk",
                            TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc_japan3 <- all_results_df_hcc_japan2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  tidylog::left_join(snp_info%>%
                       dplyr::select(rsid, snp_name, genes), by = c("snp"="snp_name")) %>%
  ungroup()
## Latino 

all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  dplyr::select(exposure, snp,term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_")) 


all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |> 
  mutate(
    effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                            str_detect(term, "^x")   ~ "Genetic Risk",
                            TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc_latino3 <- all_results_df_hcc_latino2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  tidylog::left_join(snp_info%>%
                       dplyr::select(rsid, snp_name, genes), by = c("snp"="snp_name")) %>%
  ungroup()

all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(genes, "(", " PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(genes, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(genes, "*",
                                                                       "PFAS Interaction")))

all_result_new <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(snp, " (", "PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(snp, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(snp, "*",
                                                                       "PFAS Interaction")), 
         genes = if_else(is.na(genes), snp, genes), 
         rsid = if_else(is.na(rsid), snp, rsid) ) 

# Calculate adjusted p-values
intef <- all_result_new |> 
  # tidylog::filter(effect_type == "PFAS and SNP") |>
  group_by(type) |> 
  mutate(p_adjust2 = p.adjust(p.value, method = "fdr")) |> 
  ungroup()

pfhpa_gene_interaction <- intef |> 
  tidylog::filter(effect_type == "PFAS and SNP") |>
  tidylog::filter(str_detect(exposure, "PFHpA"), 
                  type == "All races") 

min(pfhpa_gene_interaction$p_adjust2)
min(pfhpa_gene_interaction$p_adjusted)
# .12

# writexl::write_xlsx(all_result_new, fs::path(dir_result, "PFAS and SNP interaction.xlsx"))
```


# Examine PFHpA Interaction results
```{r}
pfhpa_gene_interaction <- all_result_new |> 
  tidylog::filter(str_detect(exposure, "PFHpA"), 
                  # effect_type == "PFAS and SNP", 
                  type == "All races") |> 
  mutate(effect_type = fct_relevel(effect_type, 
                                   "PFAS", "Genetic Risk", "PFAS and SNP"))

sig_int <- pfhpa_gene_interaction |> 
  tidylog::filter(effect_type == "PFAS and SNP", p.value < 0.1) 

# save file
# write_csv(sig_int |> select(rsid, genes, p.value), 
#           fs::path(dir_result, "Significant PFHpA x SNP interactions.csv"))

# Create dataset for viewing #
pfhpa_gxe_w <- pfhpa_gene_interaction |> 
  # tidylog::filter(snp %in% sig_int$snp) |>
  tidylog::select(exposure, effect_type,
                  rsid, genes, odds_ratio, p.value, type) |> 
  pivot_wider(names_from = effect_type, values_from = c(odds_ratio, p.value)) 

pfhpa_gxe_w$`p.value_PFAS and SNP`[pfhpa_gxe_w$genes == "PNPLA3"]
# View(pfhpa_gene_interaction)

# Plot 
pfhpa_gene_interaction |> 
  mutate(gene_snp = str_c(rsid, "\n", genes)) |>
  tidylog::filter(snp %in% sig_int$snp) |>  
  ggplot(aes(x = effect_type, 
             y = odds_ratio, 
             color = p.value < 0.05)) +
  geom_point(position = position_dodge(width = .3)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high), width = 0) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  facet_grid(~gene_snp) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  labs(title = "PFHpA and SNP Interaction",
       x = "Effect",
       y = "Odds Ratio",
       color = "Significance") +
  scale_color_manual(values = c("grey60", "black"))


# Final plot
pfhpa_gene_interaction |> 
  mutate(gene_snp = str_c(rsid, " (", genes, ")", sep = "")) |>
  tidylog::filter(snp %in% sig_int$snp) |>  
  ggplot(aes(y = fct_rev(effect_type), 
             x = odds_ratio)) +
  geom_point(position = position_dodge(width = .3)) +
  geom_errorbar(aes(xmin = exp_ci_low, xmax = exp_ci_high), width = 0) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  facet_wrap(~gene_snp, ncol = 1) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  labs(#title = "PFHpA and SNP Interaction",
    y = NULL,
    x = "Odds Ratio (95% CI)",
    color = "Significance") 

```

# Full model- all snps in 1 model (doesn't work- pfhpa is non-sig)

```{r}
final_mod <- clogit(
  status ~ v1 + v2 + v3 + v4 + v5 +  v6 + 
    pfas_lg2_PFHpA * (x10_112187282 + #GPAM
                        x16_53772541 + # FTO 
                        x19_19434290 + # GATAD2A
                        x19_54173068 + # TMC4
                        x22_43928850)  +
    alcohol_intake + smokestatus +
    q1_dp_amds_totscore +
    q1_fdgp7 + 
    strata(setnum), 
  data = data_hcc,
  method = "efron",
  robust = TRUE) 

# table(data_hcc$x22_43928850>.5, data_hcc$x10_112187282 > 0.5) |> 
#   chisq.test()

# Get conf int, select key terms, add metadata 
fm_ee1 <- final_mod |> 
  broom::tidy(conf.int = TRUE) |> 
  mutate(odds_ratio  = exp(estimate), 
         exp_ci_low  = exp(conf.low),
         exp_ci_high = exp(conf.high)) |> 
  tidylog::filter(
    str_detect(term, "pfas_") |
      str_detect(term, "x1") |
      str_detect(term, "x2")) |>
  mutate(effect_type = if_else(str_detect(term, ":"), 
                               "Interaction", 
                               "Main Effect"))


# Get cleaned snp and term names
fm_ee2 <- fm_ee1 |>
  tidyr::separate_wider_delim(
    term,
    delim = ":", 
    names = c("first_eff", "second_eff"), 
    too_few = "align_start") |> 
  mutate(term = if_else(is.na(second_eff), 
                        first_eff, 
                        second_eff)) |> 
  tidylog::select(term, effect_type, everything(), 
                  -first_eff, -second_eff)


# merge SNP names
fm_ee <- fm_ee2 %>%
  tidylog::left_join(snp_info, by = c("term" = "snp_name")) |>
  mutate(gene_snp = if_else(is.na(genes), "PFHpA", 
                            str_c(rsid, " (", genes, ")", sep = "")))


# Plot
fm_ee |> 
  # mutate(gene_snp = str_c(rsid, "\n", genes)) |>
  ggplot(aes(y = effect_type, 
             x = odds_ratio)) +
  geom_point(position = position_dodge(width = .3)) +
  geom_errorbar(aes(xmin = exp_ci_low, xmax = exp_ci_high), width = 0) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  facet_wrap(~ gene_snp, scales = "free_y", ncol = 1) +
  # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0)) +
  labs(title = "PFHpA and SNP Interaction",
       x = "Effect",
       y = "Odds Ratio",
       color = "Significance") 
```


