---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```

## Checking SNPs
**x14_94378610, x17_66214462, x19_19268740 were excluded from analysis**
```{r correlation of SNPs}
pfc_chem_summaries <-  data_hcc %>%
  select(x1_220796686:x22_43928850) %>%
  pivot_longer(cols = x1_220796686:x22_43928850) %>% 
  group_by(name) %>% 
  summarise(pctna   = mean(value == 0, na.rm = TRUE), 
            variance = var(value, na.rm = TRUE),
            mean    = mean(value, na.rm = TRUE))


snp_name_df <- pfc_chem_summaries %>% 
  filter(pctna < 0.75) %>% select(name)

snp_name_scld <- paste0(snp_name_df$name, "_scld")
```

## summary of SNPs
```{r summary of SNPs}
summarytools::view(summarytools::dfSummary(data_hcc%>% select(snp_name_df$name),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")
```

## summary of SNPs after normalized
```{r summary of SNPs after normalized}
data_analysis_hcc_snp <- data_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_snp <- data_nafld_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_snp <- data_other_hcc%>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_hcc_japan_snp <- data_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_japan_snp <- data_nafld_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_japan_snp <- data_other_hcc%>%
  filter(eth == "Japanese American") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 
  
data_analysis_hcc_latino_snp <- data_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_nafld_hcc_latino_snp <- data_nafld_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

data_analysis_other_hcc_latino_snp <- data_other_hcc%>%
  filter(eth == "Latino") %>%
  # rename_at(.vars = vars(colnames(data_hcc %>% select(x1_220796686:x22_43928850))),
  #           .funs = list(~str_sub(., start = 1, end = 8))) %>%
  mutate_at(.vars = vars(snp_name_df$name),
            .funs = list(scld = ~scale(.))) 

summarytools::view(summarytools::dfSummary(data_analysis_hcc_japan_snp%>% select(contains("scld"), -contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")


summarytools::view(summarytools::dfSummary(data_analysis_hcc_latino_snp%>% select(contains("scld"),-contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")

summarytools::view(summarytools::dfSummary(data_analysis_hcc_snp%>% select(contains("scld"),-contains("pfas")),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")

```


## Analysis1: HCC
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
 
covariate_input <- " alcohol_intake +  smokestatus + alcohol_intake + q1_dp_amds_e_totscore + q1_fdgp7" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
snp_name <- tibble(snp = snp_name_scld)

pfas_snp <- expand_grid(pfas_names, snp_name) %>%
  mutate(pfas_snp = paste(exposure,"*",snp)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_snp,covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         "+", pfas_snp,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 


ind_vars$clogit_out1 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_japan_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 


ind_vars$clogit_out2 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_analysis_hcc_latino_snp,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>% 
  unnest(clogit_out1) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))



all_results_df_hcc_latino <- ind_vars %>% 
  unnest(clogit_out2) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  select(exposure, snp, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                                 str_detect(term, "^x")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc3 <- all_results_df_hcc2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup() %>%
  tidylog::left_join(snp_info%>%
                       dplyr::select(rsid, snp_name, genes), by = c("snp"="snp_name"))
  
### Japanese American
all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  select(exposure, snp,term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                                 str_detect(term, "^x")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc_japan3 <- all_results_df_hcc_japan2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  tidylog::left_join(snp_info%>%
                       select(rsid, snp_name, genes), by = c("snp"="snp_name")) %>%
  ungroup()
## Latino 

all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  select(exposure, snp,term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_")) 


all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                                 str_detect(term, "^x")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc_latino3 <- all_results_df_hcc_latino2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  tidylog::left_join(snp_info%>%
                       select(rsid, snp_name, genes), by = c("snp"="snp_name")) %>%
    ungroup()

all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(genes, "(", " PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(genes, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(genes, "*",
                                                                       "PFAS Interaction")))

all_result_new <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(snp, " (", "PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(snp, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(snp, "*",
                                                                       "PFAS Interaction")))

writexl::write_xlsx(all_result_new, fs::path(dir_result, "PFAS and SNP interaction.xlsx"))
```

