---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```


## Analysis1: Interaction of PFHpA and PNPLA3 with HCC
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
 
covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = "pfas_lg2_PFHpA")

## create dataframe with names of PRS vars ----
snp_name <- tibble(snp = "x22_43928850")

pfas_snp <- expand_grid(pfas_names, snp_name) %>%
  mutate(pfas_snp = paste(exposure,"*",snp)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_snp,covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         "+", pfas_snp,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

model <- clogit(status ~ v1 + v2 + v3 + v4 + v5 + v6  +  pfas_lg2_PFHpA * x22_43928850 +  alcohol_intake + scale(bmi) + diabetes + smokestatus +strata(setnum),
                data = data_hcc,
                method = "efron",
                robust = TRUE)

res <- emtrends(model, ~x22_43928850, var = "pfas_lg2_PFHpA", 
                at = list(x22_43928850 = c(0, 2))) %>% 
  data.frame() %>% 
  select(x22_43928850, pfas_lg2_PFHpA.trend, asymp.LCL, asymp.UCL) %>%
  rename(estimate = pfas_lg2_PFHpA.trend,
         conf_low = asymp.LCL,
         conf_high = asymp.UCL)%>%
  mutate(type = ifelse(x22_43928850== 0, 
                       "Low-risk variant", 
                       "High-risk variant"))
  
res_pfhpa <- epiomics::owas_clogit(data_hcc , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = "pfas_lg2_PFHpA",
                                    conf_int = TRUE) %>%
  mutate(type = "Without accounting for genetic risk") %>%
  bind_rows(res) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         group = if_else(str_detect(type, "Without"), "overall", "with genetic")) 

(pfhpa_hcc_main <- res_pfhpa  %>%
  ggplot(aes(x = factor(type, 
                        levels = c("High-risk variant", 
                                     "Low-risk variant", 
                                     "Without accounting for genetic risk")),
                        y = exp(estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Original Effect Est.", "Effect Est. if reference polymorphism", "Effect Est. if high-risk polymorphism")), scales = "free_y")+
  facet_grid(group ~ ., scales = "free_y", space = "free_y")+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_blank(),
        # strip.text.x = element_blank(),
        text = element_text(size = 12),
        # axis.text.x =element_text(angle = 60, hjust = 1),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank())+
  coord_flip()
  )

# ggsave(filename = fs::path(dir_figures,
#                              "figures",
#                              "Fig2. Interaction of PFHpA with PNPLA3.jpeg"),
#        width =5,
#        height = 2,
#        dpi = 600,
#        bg = "white")
```

# Association between plasma PFAS and HCC risk
```{r}
res_hcc <- epiomics::owas_clogit(data_hcc , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = "Overall")

eth_categories <- unique(data_hcc$eth)

for(race in eth_categories[c(1,2)]) {
  res_hcc_temp <- epiomics::owas_clogit(data_hcc %>% filter(eth == race) , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = race)
  res_hcc <- res_hcc %>% bind_rows(res_hcc_temp)
}


# reorder PFAS by estimate
res_hcc1 <- res_hcc |> 
  mutate(pfas_name = str_remove(feature_name, "pfas_lg2_"),
         sig = case_when(adjusted_pval < 0.05 ~
                           "Sig.",
                          TRUE~ "Not Sig.")) 
# writexl::write_xlsx(all_results_df_hcc, fs::path(dir_result, "1_single_exposure_analysis_result_hcc.xlsx"))
```

