---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("!functions.R")))
source(fs::path(here::here("!load_data.R")))

data_hcc$q1_d_chol = scale(data_hcc$q1_d_chol)
data_hcc$q1_elih_imputed = scale(data_hcc$q1_elih_imputed)

```


## Analysis1: HCC
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
 
covariate_input <- " smokestatus_imputed +  q1_d_chol + q1_elih_imputed" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
race_name <- tibble(race = "eth")

pfas_race <- expand_grid(pfas_names, race_name) %>%
  mutate(pfas_race = paste(exposure,"*",race)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_race,covar_names) |>  
  mutate(formula = paste("status ~ ", pfas_race,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_hcc,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl(":", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))

```

## Meta-analysis
```{r meta analysis}
res_hcc <- epiomics::owas_clogit(data_hcc , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = "Overall")

eth_categories <- unique(data_hcc$eth)

for(race in eth_categories[1:4]) {
  res_hcc_temp <- epiomics::owas_clogit(data_hcc %>% filter(eth == race) , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = race)
  res_hcc <- res_hcc %>% bind_rows(res_hcc_temp)
}


# reorder PFAS by estimate
res_hcc1 <- res_hcc |> 
  mutate(pfas_name = str_remove(feature_name, "pfas_lg2_"),
         sig = case_when((p_value < 0.05 & adjusted_pval < 0.05) ~
                           "FDR p value < 0.05",
                          p_value < 0.05 ~ "p value < 0.05", 
                         p_value >= 0.05 ~ "p value ≥ 0.05"),
         sig = factor(sig, levels = c("p value ≥ 0.05", "p value < 0.05", "FDR p value < 0.05"))) %>%
  mutate(covar = sub(".*~(.*?)\\+pfas.*", "\\1", formula))%>%
  select(covar, everything())


meta_df <- res_hcc1 %>% select(pfas_name, type, estimate, se_est)%>%
  mutate(vi = se_est^2) %>%
  select(-se_est)

# write_csv(meta_df, fs::path(dir_result, "meta_df.csv"))

res_df <- data.frame()

# Function to fit model and test heterogeneity for each PFAS
analyze_pfas <- function(pfas, data) {
  # Subset data for the current PFAS
  
  subset_data <- subset(data, pfas_name == pfas)%>%
    select(-pfas_name)
  
  # Fit the random-effects model
  model <- rma(yi = estimate, vi = vi, data = subset_data, method = "REML")
  
  # Calculate and print the I^2 statistic
  # I2 <- model$I2
  # cat("I^2 for", pfas_name, ":", I2, "\n")
  model_summary <- summary(model)
  # Test for heterogeneity
  # heterogeneity_test <- anova(model)
  # cat("Heterogeneity test for", pfas, ":\n")
  # print(heterogeneity_test)
  # Store results in a list
  res_df <- data.frame(
    pfas = pfas,
    tau2 = model_summary$tau2,
    I2 = model_summary$I2,
    H2 = model_summary$H2,
    Q = model_summary$QE,
    Q_df = model_summary$k - 1,
    Q_pval = model_summary$QEp,
    pooled_lg_or = model_summary$b,
    se = model_summary$se,
    pval_model = model_summary$pval,
    pooled_ci.lb = model_summary$ci.lb,
    pooled_ci.ub = model_summary$ci.ub
  )
  return(res_df)
}

# Apply the function to each PFAS
for (pfas in unique(meta_df$pfas_name)) {
  print(pfas)
  temp_df <- analyze_pfas(pfas, meta_df)
  res_df <- res_df %>% bind_rows(temp_df)
}

res_df1 <- res_df %>% 
  mutate(or_ci = paste0(round(exp(pooled_lg_or),2), " [", 
                        round(exp(pooled_ci.lb),2), ", ", 
                        round(exp(pooled_ci.ub),2), "]"))%>%
  rename(pfas_name = pfas) %>%
  mutate(pfas_name = case_when(pfas_name == "4H_PFBA" ~ "4H-PFBA",
                               pfas_name == "10_2_FToH" ~ "10:2 FTOH",
                               pfas_name == "2_aminohexafluoropropan_2_ol" ~ "2-Aminohexafluoropropan-2-ol",
                               pfas_name == "Me_PFHxA" ~ "MePFHxA",
                               TRUE ~ pfas_name))

writexl::write_xlsx(res_df1, fs::path(dir_result, "heterogeneity_res.xlsx"))
```


