---
title: "6_Identify liver eQTLs from GTEx"
author: "Jesse Goodrich"
date: "2024-08-22"
output: html_document
---

```{r setup, include=FALSE}
# Setup ptoject
source(here::here("!libraries.R"))
source(here::here("!directories.R"))

# read file
snp_gene_df <- read_csv(
  fs::path(dir_result, 
           "Significant PFHpA x SNP interactions.csv"))

# Select positive interactions only
snp_gene_df <- snp_gene_df |> 
  tidylog::filter(odds_ratio > 1)

epiomics::meet_m

# Read eQTLs from FIVEx
eqtl_df <- readxl::read_xlsx(fs::path(dir_data,
                                      "eQTLs",
                                      "raw_eqtls_from_fivex.xlsx")) 

# eqtl_df_w <- eqtl_df |>
#   dplyr::summarise(n = dplyr::n(), .by = c(rsid, colname)) |>
#   tidylog::filter(n > 1L, rsid %in% snp_gene_df$rsid) 


eqtl_df_w <- eqtl_df |>
  pivot_wider(names_from = "colname", values_from = "value") |> 
  janitor::clean_names() |> 
  select(-group) |> 
  tidylog::filter(rsid %in% snp_gene_df$rsid) 

length(unique(eqtl_df_w$rsid))

# Change to numeric values
eqtl_df_w <- eqtl_df_w |> 
  tidylog::mutate(neg_log_p = as.numeric(neg_log_p), 
                  eff_size = as.numeric(eff_size), 
                  se_eff_size = as.numeric(se_eff_size), 
                  pip = as.numeric(pip) , 
                  cs_size = as.numeric(cs_size), 
                  p_value = 10^(-1*neg_log_p)) |> 
  tidylog::filter(p_value < 0.05) 

# Remove sex specific organs
eqtl_df_w_clean <- eqtl_df_w |> 
  # tidylog::filter(system != "Reproductive", 
  #                 system != "Mammary") |>
  tidylog::filter(system %in% c(#"Adipose",            
    "Immune",
    "Blood",
    "Cell Culture",
    "Liver"))
# "Blood Vessel",
# "Reproductive",
# "Esophagus",
# "Heart",
# "Pancreas",
# "Spleen",
# "Stomach",
# "Brain",
# "Colon",
# "Muscle",
# "Mammary",
# "Nerve",
# "Adrenal Gland",
# "Minor Salivary Gland",
# "Lung",
# "Pituitary",
# "Thyroid",
# "Kidney",
# "Small Intestine"))

# Number of genes this removed: 
length(unique(eqtl_df_w$gene))-length(unique(eqtl_df_w_clean$gene))


# Create rsid/gene key for comptoxai analysis ----
eqtls_clean <- eqtl_df_w_clean |> 
  group_by(rsid, gene) |> 
  slice_head() |> 
  select(rsid, gene) |> 
  mutate(rel = "eQTL")


# Add genes associated with the actual SNPS- expand across ; in genes 
snp_gene_df_l <- snp_gene_df |>
  dplyr::mutate(gene = strsplit(genes, "; ")) |>
  tidyr::unnest(cols = gene) |> 
  dplyr::select(-genes, -p.value, -odds_ratio) |> 
  mutate(rel = "Gene: SNP associated gene")

snp_gn_df <- bind_rows(eqtls_clean, snp_gene_df_l)

write_csv(snp_gn_df, 
          fs::path(dir_data, 
                   "eQTLs",
                   "eqtl_rsid_pairs.csv"))
length(unique(snp_gn_df$rsid))
```


# None of these genes were identified in vitro though: 
```{r}
sc_data <- read_csv(
  fs::path(dir_home,
           "6_scRNAseq organoid data",
           "Excel Supplement B genes brittneys paper.csv"))

length(unique(sc_data$gene))/nrow(sc_data)
table(sc_data$cell_type)
table(sc_data$gene %in% eqtl_df_w_clean$gene)
```

