---
title: 'LUCID analysis - MEC'
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"

output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{css, echo=FALSE}
pre {
  max-height: 200px;
  overflow-: auto;
}
```

```{r lucid analysis setup, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("LUCIDus Sankey fxn.R")))
```


```{r LUCID analysis load data}
data <- readRDS(fs::path(
          dir_cleaned_data,
          "p27_hhear_pfas_covar_imputed_V2.RDS"))
ftr_data <- readRDS(fs::path(
          dir_cleaned_data,
          "Untargeted_feature_tables_filtered_lg2.RDS"))

meta_name <- readRDS(fs::path(
          dir_cleaned_data,
          "feature_metadata_untargeted.RDS")) %>% 
  filter(!is.na(metabolites_name))

ftr_data_annotated <- ftr_data %>% 
  select(id, meta_name$name)%>%
  mutate(sid = str_split_fixed(id, "_",2)[,1],
         rep = str_split_fixed(id, "_",2)[,2]) %>%
  filter(rep == "1") %>% 
  select(where(function(x) !all(is.na(x)))) %>%
  select(-rep, -id) %>% 
  tidylog::left_join(ftr_data %>% 
                       select(id, meta_name$name)%>%
                       mutate(sid = str_split_fixed(id, "_",2)[,1],
                              rep = str_split_fixed(id, "_",2)[,2]) %>%
                       filter(rep == "2") %>% 
                       select(where(function(x) !all(is.na(x)))) %>%
  select(-rep, -id), by = "sid")

full_data <- data %>% labelled::remove_labels() %>%
  tidylog::left_join(ftr_data_annotated, 
                                         by = "sid")

pfas_name <- c("pfas_pfda_imputed","pfas_pfos_imputed","pfas_pfhpa_imputed",
               "pfas_pfhxs_imputed","pfas_pfhps_imputed","pfas_pfna_imputed",
               "pfas_pfoa_imputed","pfas_pfuda_imputed",
               "pfas_pfds_detect", "pfas_pfpes_detect",
               "pfas_pftrda_detect")
covars <- c("blood_age", "eth", "sex", "studyarea")
```

## Data preparation

1) HCC data: sample size 240
2) NAFLD-related  HCC data : sample size 97 
3) other  HCC data : sample size 143 

```{r data preparation}
sample_id1 <- full_data %>% filter(status == "HCC") %>% select(setnum)
sample_id2 <- full_data %>% filter(casetype == "NAFLD-related HCC") %>% select(setnum)
sample_id3 <- full_data %>% filter(casetype == "Other HCC") %>% select(setnum)
data_analysis1 <- full_data %>% filter(setnum %in% sample_id1$setnum)
data_analysis2 <- full_data %>% filter(setnum %in% sample_id2$setnum)
data_analysis3 <- full_data %>% filter(setnum %in% sample_id3$setnum)

data_analysis_hcc <- data_analysis1 %>% 
  mutate_at(.vars = pfas_name[1:8],
            .funs = list(scld = ~scale(.),
                         lg2 = ~log2(.), 
                         median = ~ifelse(. < quantile(., 0.5, na.rm = TRUE), 0, 1),
                         `85pct` = ~ifelse(. < quantile(., 0.85, na.rm = TRUE), 0, 1))) %>%
  mutate(status = ifelse(status== "Control", 0, 1)) %>%
  mutate_at(.vars = c("pfas_pfds_detect", "pfas_pfpes_detect", "pfas_pftrda_detect"),
            .funs = ~factor(., levels = c("non_detected", "detected")))

data_analysis_nafld_hcc <- data_analysis2 %>% 
  mutate_at(.vars = pfas_name[1:8],
            .funs = list(scld = ~scale(.),
                         lg2 = ~log2(.), 
                         median = ~ifelse(. < quantile(., 0.5, na.rm = TRUE), 0, 1),
                         `85pct` = ~ifelse(. < quantile(., 0.85, na.rm = TRUE), 0, 1))) %>%
  mutate(status = ifelse(status== "Control", 0, 1)) %>%
  mutate_at(.vars = c("pfas_pfds_detect", "pfas_pfpes_detect", "pfas_pftrda_detect"),
            .funs = ~factor(., levels = c("non_detected", "detected")))

data_analysis_other_hcc <- data_analysis3 %>% 
  mutate_at(.vars = pfas_name[1:8],
            .funs = list(scld = ~scale(.),
                         lg2 = ~log2(.), 
                         median = ~ifelse(. < quantile(., 0.5, na.rm = TRUE), 0, 1),
                         `85pct` = ~ifelse(. < quantile(., 0.85, na.rm = TRUE), 0, 1))) %>%
  mutate(status = ifelse(status== "Control", 0, 1)) %>%
  mutate_at(.vars = c("pfas_pfds_detect", "pfas_pfpes_detect", "pfas_pftrda_detect"),
            .funs = ~factor(., levels = c("non_detected", "detected")))

```


## Meet in the middle analysis
```{r meet in the middle}
# metabolome-------
## omics-exposure----
result <- epiomics::meet_in_middle(
  df = data_analysis_hcc,
  exposure = "pfas_pfhpa_imputed_scld",
  outcome = "status",
  omics = meta_name$name,
  covars = covars,
  outcome_family = "binomial")

meta_name %>% filter(name %in% result$overlap$feature_name) %>% select(name, metabolites_name)
```


## LUCID analysis1

**Exposure: PFHpA PFOA PFOS**

**Omics: annotated omics feature**

**Outcome: HCC**

**Covars: age eth sex studysite**

```{r lucid analysis, echo = FALSE, warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE}
# G  = scale(df_model %>% select(all_of(all_legacy_pfas)))
data_analysis_hcc_lucid <- data_analysis_hcc %>% 
  drop_na(blood_age, eth, sex, studyarea,
          pfas_pfhpa_imputed_scld, pfas_pfoa_imputed_scld,
          pfas_pfos_imputed_scld, pfas_pfhps_imputed_scld,
          meta_name$name)


G_pfhpa  = data_analysis_hcc_lucid$pfas_pfhpa_imputed_scld
# G_pfos = data_analysis_hcc_lucid$pfas_pfos_imputed_scld
# G_pfoa =data_analysis_hcc_lucid$pfas_pfoa_imputed_scld
# G_pfhps =data_analysis_hcc_lucid$pfas_pfhps_imputed_scld

Z = scale(data_analysis_hcc_lucid %>% select(result$overlap$feature_name[-3]))

Y = data_analysis_hcc_lucid$status

covs <- data_analysis_hcc_lucid %>% select(blood_age, eth, sex, studyarea) %>%
  fastDummies::dummy_cols( 
                          select_columns = c("eth", "sex", "studyarea"),
                          remove_selected_columns = TRUE,
                          remove_first_dummy = TRUE) 

fit_pfhpa  <- lucid(G = G_pfhpa,
              Z = Z,
              Y = Y, 
              K = 2,
              # CoY = covs,
              # CoG = covs,
              useY = TRUE,
              init_par = "random",
              # family = "normal",
              family = "binary",
              # modelName = rep("VEI", 1)
              # Rho_Z_Mu = 10,
              # Rho_Z_Cov = .5,
              seed = 1008
              ) 

# fit_pfoa <- lucid(G = G_pfoa,
#               Z = Z,
#               Y = Y, 
#               K = 2,
#               # CoY = covs,
#               # CoG = covs,
#               useY = TRUE,
#               init_par = "random",
#               # family = "normal",
#               family = "binary",
#               # modelName = rep("VEI", 1)
#               # Rho_Z_Mu = 10,
#               # Rho_Z_Cov = .5,
#               seed = 1008
#               ) 

# fit_pfos <- lucid(G = G_pfos,
#               Z = Z,
#               Y = Y, 
#               K = 2,
#               # CoY = covs,
#               # CoG = covs,
#               useY = TRUE,
#               init_par = "random",
#               # family = "normal",
#               family = "binary",
#               # modelName = rep("VEI", 1)
#               # Rho_Z_Mu = 10,
#               # Rho_Z_Cov = .5,
#               seed = 1008
#               ) 
# 
# fit_pfhps <- lucid(G = G_pfhps,
#               Z = Z,
#               Y = Y, 
#               K = 2,
#               # CoY = covs,
#               # CoG = covs,
#               useY = TRUE,
#               init_par = "random",
#               # family = "normal",
#               family = "binary",
#               # modelName = rep("VEI", 1)
#               # Rho_Z_Mu = 10,
#               # Rho_Z_Cov = .5,
#               seed = 1008
#               ) 
```

## Sankey Diagram
```{r sankey diagram }
# Colors ----
col_pal <- RColorBrewer::brewer.pal(n = 8, name = "Dark2")

# Color pallet for sankey
sankey_colors <- matrix(c("exposure", col_pal[2],
                          "lc",      col_pal[1],
                          "biomarker", "#7A4988",
                          "Outcome",  "#5A5A5A",
                          "TRUE",     "#6372e0", # Blue
                          "FALSE",    "#d1d4ff", # Light grey
                          "pos_clus_to_out", "red", 
                          "neg_clus_to_out", "#e4e5f2"), 
                        byrow = TRUE, nrow = 8) |> 
  as_tibble(.name_repair = "universal") |>
  janitor::clean_names() |>
  rename("domain" = x1, 
         "range" = x2)

(p1 <- sankey_diagram_plotly(fit_pfhpa, text_size = 15, exposure = "PFHpA"))

# (p2 <- sankey_diagram_plotly(reorder_lucid(fit_pfoa,c(2,1)),
#                              text_size = 15, 
#                              exposure = "PFOA"))
# 
# (p3 <- sankey_diagram_plotly(reorder_lucid(fit_pfos,c(2,1)), text_size = 15, exposure = "PFOS"))
# 
# (p4 <- sankey_diagram_plotly(reorder_lucid(fit_pfos,c(2,1)), text_size = 15, exposure = "PFHpS"))
```