---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```



## Analysis1: HCC
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
 
covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
snp_name <- tibble(snp = snp_name_df$name)

pfas_snp <- expand_grid(pfas_names, snp_name) %>%
  mutate(pfas_snp = paste(exposure,"*",snp)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_snp,covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         "+", pfas_snp,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_hcc,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))


## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("x", term)) %>%
  select(exposure, snp, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and SNP",
                                 str_detect(term, "^x")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type)) 

all_results_df_hcc3 <- all_results_df_hcc2 %>% 
  filter(!grepl("x14", term)) |>
  group_by(pfas_name) %>%
  mutate(snp = str_replace_all(snp, "_scld", ""),
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup() %>%
  tidylog::left_join(snp_info%>%
                       dplyr::select(rsid, snp_name, genes), by = c("snp"="snp_name"))
  
all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(genes, "(", " PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(genes, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(genes, "*",
                                                                       "PFAS Interaction")))

all_result_new <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ paste0(snp, " (", "PFAS Main Effect)"),
                                effect_type == "Genetic Risk" ~ paste0(snp, " Main Effect"),
                                effect_type == "PFAS and SNP" ~ paste0(snp, "*",
                                                                       "PFAS Interaction")))

# writexl::write_xlsx(all_result_new, fs::path(dir_result, "PFAS and SNP interaction.xlsx"))
```


### Fig 1. SNP main Effect
```{r result snp hcc, fig.width= 15, fig.height=7}

## PFHpA
(plot1 <- all_result_new %>%
     filter(pfas_name == "PFHpA"&type == "All races"&genes %in% c("PNPLA3")&term == "x22_43928850")%>% 
    # mutate(name = case_when(grepl("Interaction", name_plot) ~ "SNP * PFHpA Interaction",
    #                         grepl("PFAS", name_plot) ~ "PFHpA Main Effect",
    #                         TRUE ~ "SNP Main Effect"),
    #        name = factor(name, levels = c("SNP * PFHpA Interaction", "SNP Main Effect", "PFHpA Main Effect")))%>%
     ggplot(aes(x = fct_rev(genes), y = odds_ratio)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey50") +
  # coord_flip() +
  # facet_wrap(rsid ~ ., scales = "free", ncol = 1)+
  theme(
        # axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
        legend.position = "none",
        panel.background = element_rect(fill="white"),
        strip.background = element_rect(fill = "white"),
        # strip.text.y = element_blank(),
        # strip.text.y = element_text(angle = 90),
        # strip.text.x = element_blank(),
        text = element_text(size = 10),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
      ylab("Odds Ratio for HCC \n (95% CI)") )
  # ggtitle("PFHpA and SNP") +
  # scale_color_manual(values = c("purple", "black","red")))


# (fig <- cowplot::plot_grid(plot1, 
#                            plot2,
#                            ncol = 1, 
#                            rel_heights = c(0.2, 0.2),
#                            labels = c("A.",
#                                       "B."),
#                           # label_x = c(-0.08,-0.18),
#                           label_size = 10,
#                           align = "v",
#                           axis = "lt"))
  ggsave(filename = fs::path(dir_figures,
                             "conference",
                             "Fig1. SNP and HCC.jpeg"),
       width =2,
       height = 2,
       dpi = 600,
       bg = "white")
```


## Analysis1: Interaction of PFHpA and PNPLA3 with HCC
* Model1: outcome ~ one pfas + one SNP + pfas * snp
```{r interaction between PFAS and SNPs hcc}
 
covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = "pfas_lg2_PFHpA")

## create dataframe with names of PRS vars ----
snp_name <- tibble(snp = "x22_43928850")

pfas_snp <- expand_grid(pfas_names, snp_name) %>%
  mutate(pfas_snp = paste(exposure,"*",snp)) 

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_snp,covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         "+", pfas_snp,
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

model <- clogit(status ~ v1 + v2 + v3 + v4 + v5 + v6  +  pfas_lg2_PFHpA * x22_43928850 +  alcohol_intake + scale(bmi) + diabetes + smokestatus +strata(setnum),
                data = data_hcc,
                method = "efron",
                robust = TRUE)

res <- emtrends(model, ~x22_43928850, var = "pfas_lg2_PFHpA", 
                at = list(x22_43928850 = c(0, 2))) %>% 
  data.frame() %>% 
  select(x22_43928850, pfas_lg2_PFHpA.trend, asymp.LCL, asymp.UCL) %>%
  rename(estimate = pfas_lg2_PFHpA.trend,
         conf_low = asymp.LCL,
         conf_high = asymp.UCL)%>%
  mutate(type = ifelse(x22_43928850== 0, 
                       "Low-risk variant", 
                       "High-risk variant"))
  
res_pfhpa <- epiomics::owas_clogit(data_hcc , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = "pfas_lg2_PFHpA",
                                    conf_int = TRUE) %>%
  mutate(type = "Without accounting for genetic risk") %>%
  bind_rows(res) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         group = if_else(str_detect(type, "Without"), "overall", "with genetic")) 

(pfhpa_hcc_main <- res_pfhpa  %>%
  ggplot(aes(x = factor(type, 
                        levels = c("High-risk variant", 
                                     "Low-risk variant", 
                                     "Without accounting for genetic risk")),
                        y = exp(estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Original Effect Est.", "Effect Est. if reference polymorphism", "Effect Est. if high-risk polymorphism")), scales = "free_y")+
  facet_grid(group ~ ., scales = "free_y", space = "free_y")+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_blank(),
        # strip.text.x = element_blank(),
        text = element_text(size = 12),
        # axis.text.x =element_text(angle = 60, hjust = 1),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank())+
  coord_flip()
  )

ggsave(filename = fs::path(dir_figures,
                             "figures",
                             "Fig2. Interaction of PFHpA with PNPLA3.jpeg"),
       width =5,
       height = 2,
       dpi = 600,
       bg = "white")
```

# Association between plasma PFAS and HCC risk
```{r}
res_hcc <- epiomics::owas_clogit(data_hcc , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = "Overall")

eth_categories <- unique(data_hcc$eth)

for(race in eth_categories[c(1,2)]) {
  res_hcc_temp <- epiomics::owas_clogit(data_hcc %>% filter(eth == race) , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = covars,
                                    omics = pfas_name,
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = race)
  res_hcc <- res_hcc %>% bind_rows(res_hcc_temp)
}


# reorder PFAS by estimate
res_hcc1 <- res_hcc |> 
  mutate(pfas_name = str_remove(feature_name, "pfas_lg2_"),
         sig = case_when(adjusted_pval < 0.05 ~
                           "Sig.",
                          TRUE~ "Not Sig.")) 
# writexl::write_xlsx(all_results_df_hcc, fs::path(dir_result, "1_single_exposure_analysis_result_hcc.xlsx"))
```

### Fig1a. association of pfas and hcc - HCC
```{r plot with covars only, fig.width=10, fig.height=5}
### Create metabolites Coefficient Plots
res_hcc2 <- res_hcc1 %>%
  mutate(pfas_name = case_when(pfas_name == "4H_PFBA" ~ "4H-PFBA",
                               pfas_name == "10_2_FToH" ~ "10:2 FTOH",
                               pfas_name == "2_aminohexafluoropropan_2_ol" ~ "2-Aminohexafluoropropan-2-ol",
                               pfas_name == "Me_PFHxA" ~ "MePFHxA",
                               pfas_name == "PFHpA" ~ "PFHpA*",
                               TRUE ~ pfas_name),
         ) %>%
  mutate(pfas_name = fct_reorder(pfas_name, if_else(type == "Overall", estimate, NA_real_))) %>%
  mutate(type = case_when(type == "Overall" ~ "Overall \n(n = 474)",
                          type == "Japanese American" ~ "Japanese American \n(n = 182)", 
                        type == "Latino"~ "Latino \n(n = 160)"))



(pfhpa_hcc_main <- res_hcc2  %>%
  filter(type == "Overall \n(n = 474)")%>%
  ggplot(aes(x = pfas_name,y = exp(estimate), color = sig)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Overall \n(n = 474)", "Japanese American \n(n = 182)", "Latino \n(n = 160)")), scales = "free_y")+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "none",
        legend.title = element_blank())+
  coord_flip() +
  scale_color_manual(values = c("black","red")))


ggsave(filename = fs::path(dir_figures,
                           "conference",
                           "Fig. PFAS main effect.jpeg"),
       width = 5,
       height = 5,
       dpi = 300,
       bg = "white")
```

# Plasma pfas and hcc risk by race/ethnicity
```{r}
(pfhpa_hcc_by_race <- res_hcc2  %>%
  filter(pfas_name =="PFHpA*")%>%
  ggplot(aes(x = type,y = exp(estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Overall \n(n = 474)", "Japanese American \n(n = 182)", "Latino \n(n = 160)")), scales = "free_y")+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "none",
        legend.title = element_blank())+
  coord_flip() 
 # +
 #  scale_color_manual(values = c("black","red"))
 )


ggsave(filename = fs::path(dir_figures,
                           "conference",
                           "Fig. PFAS main effect by race.jpeg"),
       width = 4,
       height = 2.5,
       dpi = 300,
       bg = "white")
```


```

