---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup univariate analysis, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("!functions.R")))
source(fs::path(here::here("!load_data.R")))

```

## Supplemental Table1
```{r}
s1 <- readxl::read_xlsx(fs::path(dir_result, "T1.Continuous PFAS and HCC_0416.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(exp(estimate), 2), " [", 
                               round(exp(conf_low), 2), ", ",
                               round(exp(conf_high), 2),"]"),
         `P-Value` = signif(p_value, 2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`)%>%
  pivot_wider(id_cols = "pfas_name",
              names_from = "type",
              values_from = c(`Odds Ratio[95%CI]`, `P-Value`)) %>%
  # arrange(desc(`Odds Ratio[95%CI]_Overall \n(n = 474)`))
  arrange(desc(`Odds Ratio[95%CI]_Overall \r\n(n = 480)`))%>%
  mutate(pfas_name = rename_pfas(pfas_name))

s4 <- readxl::read_xlsx(fs::path(dir_result, "heterogeneity_res.xlsx")) 

s1_full <- s1 %>% 
  tidylog::left_join(s4 %>% select(pfas_name, or_ci, I2, Q, Q_pval), 
                     by = c("pfas_name"))%>%
  select(pfas_name, contains("Overall"), contains("Japanese"), 
         contains("Latino"), contains("African"), contains("White"), everything())%>%
  mutate(I2 = round(I2, 6),
         Q = round(Q,2),
         Q_pval = round(Q_pval, 2))

writexl::write_xlsx(s1_full, fs::path(dir_result, "Supplemental Tables/Table S1. PFAS and HCC_0416.xlsx")) 

```

## Supplemental Table 2
```{r s2}
s2 <- readxl::read_xlsx(fs::path(dir_result, "single_categorical_exposure_analysis_0416.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(odds_ratio, 2), " [", 
                               round(exp_ci_low, 2), ", ",
                               round(exp_ci_high, 2),"]"),
         `P-Value` = signif(p.value, 2),
         `P trend` = signif(p_trend, 2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`, `P trend`, term)%>%
  pivot_wider(id_cols = c("pfas_name", "term"),
              names_from = "type",
              values_from = c(`Odds Ratio[95%CI]`, `P-Value`, `P trend`)) %>%
  mutate(term = paste(substr(term, (nchar(term)-8), nchar(term)-1) %>% toTitleCase(), substr(term, nchar(term), nchar(term)))) %>%
  mutate(across(everything(), ~ ifelse(. == "1 [NA,NA]", "1", .)))%>%
  mutate(pfas_name = rename_pfas(pfas_name)) %>%
  mutate(pfas_name = factor(pfas_name, levels = s1$pfas_name))%>%
  arrange(pfas_name)%>%
  select(pfas_name, term, contains("Overall"), contains("Japanese"), 
         contains("Latino"))

writexl::write_xlsx(s2, fs::path(dir_result, "Supplemental Tables/Table S2. Dose response_0423.xlsx"))
```

## Supplemental Table S3
```{r}
s3 <- readxl::read_xlsx(fs::path(dir_result, "pfas_prs_interaction_result.xlsx")) %>% 
  mutate(`Odds Ratio[95%CI]` = paste0(round(odds_ratio, 2), " [", 
                               round(exp_ci_low, 2), ", ",
                               round(exp_ci_high, 2),"]"),
         `P-Value` = signif(p_value, 2))%>% 
  select(pfas, type, `Odds Ratio[95%CI]`,`P-Value`)%>%
  mutate(pfas = rename_pfas(pfas))%>%
  mutate(pfas = factor(pfas, levels = s1$pfas_name))%>%
  arrange(pfas)

writexl::write_xlsx(s3, fs::path(dir_result, "Supplemental Tables/Table S3. PFAS and PRS_0423.xlsx"))
```


## Supplemental Table S4
```{r}
s4 <- readxl::read_xlsx(fs::path(dir_result, "PFAS and SNP interaction_0421.xlsx")) %>% 
    mutate(type = case_when(type == "All races" ~ "Overall \n(n = 480)",
                          type == "Japanese American" ~ "Japanese American \n(n = 184)", 
                        type == "Latino"~ "Latino \n(n = 162)"))%>%
  mutate(name = case_when(grepl("Interaction", name_plot) ~ "SNP * PFAS Interaction",
                            grepl("PFAS", name_plot) ~ "PFAS Main Effect",
                            TRUE ~ "SNP Main Effect"),
           name = factor(name, levels = c("SNP * PFAS Interaction", "SNP Main Effect", "PFAS Main Effect"))) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(odds_ratio, 2), " [", 
                               round(exp_ci_low, 2), ", ",
                               round(exp_ci_high, 2),"]"),
         `P-Value` = signif(p.value, 2))%>% 
  select(type, pfas_name, snp, genes, name, rsid, `Odds Ratio[95%CI]`,`P-Value`)%>%
  mutate(pfas_name = rename_pfas(pfas_name))%>%
  pivot_wider(id_cols = c("type","pfas_name","snp", "genes","rsid"),
              names_from = "name",
              values_from = c(`Odds Ratio[95%CI]`, `P-Value`)) %>%
  pivot_wider(id_cols = c("pfas_name","snp", "genes", "rsid"),
              names_from = "type",
              values_from = c(`Odds Ratio[95%CI]_PFAS Main Effect`:`P-Value_SNP * PFAS Interaction`)) %>%
  mutate(pfas_name = factor(pfas_name, levels = s1$pfas_name))%>%
  arrange(pfas_name)%>%
  select(pfas_name, snp, genes, rsid, contains("PFAS Main Effect_Overall"),
         contains("SNP Main Effect_Overall"), 
         contains("SNP * PFAS Interaction_Overall"),
         contains("PFAS Main Effect_Japanese"),
         contains("SNP Main Effect_Japanese"), 
         contains("SNP * PFAS Interaction_Japanese"),
         contains("PFAS Main Effect_Latino"),
         contains("SNP Main Effect_Latino"), 
         contains("SNP * PFAS Interaction_Latino")
         )
  
writexl::write_xlsx(s4, fs::path(dir_result, "Supplemental Tables/Table S4. PFAS and SNP_0421.xlsx"))

s4_pfhpa <- s4 %>% filter(pfas_name == "PFHpA")
writexl::write_xlsx(s4, fs::path(dir_result, "Supplemental Tables/Table S4. PFHpA and SNP_0421.xlsx"))
```
