---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup univariate analysis, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("!functions.R")))
source(fs::path(here::here("!load_data.R")))

s0 <- readxl::read_xlsx(fs::path(dir_result, "T1.Continuous PFAS and HCC_0828.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(exp(estimate), 2), " [", 
                               round(exp(conf_low), 2), ", ",
                               round(exp(conf_high), 2),"]"),
         `P-Value` = signif(p_value, 2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`)%>%
  pivot_wider(id_cols = "pfas_name",
              names_from = "type",
              values_from = c(`Odds Ratio[95%CI]`, `P-Value`)) %>%
  # arrange(desc(`Odds Ratio[95%CI]_Overall \n(n = 474)`))
  arrange(desc(`Odds Ratio[95%CI]_Overall \r\n(n = 464)`))%>%
  mutate(pfas_name = rename_pfas(pfas_name))
```

## Supplemental Table1-Female
```{r}
s1 <- readxl::read_xlsx(fs::path(dir_result, "T1.Continuous PFAS and HCC_Female_0828.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(exp(estimate), 2), " [", 
                               round(exp(conf_low), 2), ", ",
                               round(exp(conf_high), 2),"]"),
         `P-Value` = signif(p_value, 2),
         `Q-Value` = signif(adjusted_pval,2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`, `Q-Value`)%>%
  mutate(pfas_name = rename_pfas(pfas_name))%>%
  mutate(pfas_name = factor(pfas_name, levels = s0$pfas_name))%>%
  arrange(pfas_name)

# s1_full <- s1 %>% 
#   tidylog::left_join(s4 %>% select(pfas_name, or_ci, I2, Q, Q_pval), 
#                      by = c("pfas_name"))%>%
#   select(pfas_name, contains("Overall"), contains("Japanese"), 
#          contains("Latino"), contains("African"), contains("White"), everything())%>%
#   mutate(I2 = round(I2, 6),
#          Q = round(Q,2),
#          Q_pval = round(Q_pval, 2))

writexl::write_xlsx(s1, fs::path(dir_result, "Supplemental Tables/Table S1. PFAS and HCC_Female_0828.xlsx")) 

```

## Supplemental Table 2-Female
```{r s2}
s2 <- readxl::read_xlsx(fs::path(dir_result, "single_categorical_exposure_analysis_Female.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(odds_ratio, 2), " [", 
                               round(exp_ci_low, 2), ", ",
                               round(exp_ci_high, 2),"]"),
         `P-Value` = signif(p.value, 2),
         `P trend` = signif(p_trend, 2),
         `Q trend` = signif(adjusted_pval, 2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`, `P trend`,`Q trend`, term)%>%
  # pivot_wider(id_cols = c("pfas_name", "term"),
  #             names_from = "type",
  #             values_from = c(`Odds Ratio[95%CI]`, `P-Value`, `P trend`)) %>%
  mutate(term = paste(substr(term, (nchar(term)-8), nchar(term)-1) %>% toTitleCase(), substr(term, nchar(term), nchar(term)))) %>%
  mutate(across(everything(), ~ ifelse(. == "1 [NA, NA]", "1", .)))%>%
  mutate(pfas_name = rename_pfas(pfas_name)) %>%
  mutate(pfas_name = factor(pfas_name, levels = s0$pfas_name))%>%
  arrange(pfas_name)%>%
  select(pfas_name, term, everything())

writexl::write_xlsx(s2, fs::path(dir_result, "Supplemental Tables/Table S2. Dose response_Female.xlsx"))
```


## Supplemental Table1-Male
```{r}
s1 <- readxl::read_xlsx(fs::path(dir_result, "T1.Continuous PFAS and HCC_Male_0828.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(exp(estimate), 2), " [", 
                                      round(exp(conf_low), 2), ", ",
                                      round(exp(conf_high), 2),"]"),
         `P-Value` = signif(p_value, 2),
         `Q-Value` = signif(adjusted_pval,2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`, `Q-Value`)%>%
  # pivot_wider(id_cols = "pfas_name",
  #             names_from = "type",
  #             values_from = c(`Odds Ratio[95%CI]`, `P-Value`)) %>%
  # arrange(desc(`Odds Ratio[95%CI]_Overall \n(n = 474)`))
  # arrange(desc(`Odds Ratio[95%CI]`))%>%
  mutate(pfas_name = rename_pfas(pfas_name))%>%
  mutate(pfas_name = factor(pfas_name, levels = s0$pfas_name))%>%
  arrange(pfas_name)

# s1_full <- s1 %>% 
#   tidylog::left_join(s4 %>% select(pfas_name, or_ci, I2, Q, Q_pval), 
#                      by = c("pfas_name"))%>%
#   select(pfas_name, contains("Overall"), contains("Japanese"), 
#          contains("Latino"), contains("African"), contains("White"), everything())%>%
#   mutate(I2 = round(I2, 6),
#          Q = round(Q,2),
#          Q_pval = round(Q_pval, 2))

writexl::write_xlsx(s1, fs::path(dir_result, "Supplemental Tables/Table S1. PFAS and HCC_Male_0828.xlsx")) 

```

## Supplemental Table 2-Male
```{r s2}
s2 <- readxl::read_xlsx(fs::path(dir_result, "single_categorical_exposure_analysis_Male.xlsx")) %>%
  mutate(`Odds Ratio[95%CI]` = paste0(round(odds_ratio, 2), " [", 
                                      round(exp_ci_low, 2), ", ",
                                      round(exp_ci_high, 2),"]"),
         `P-Value` = signif(p.value, 2),
         `P trend` = signif(p_trend, 2),
         `Q trend` = signif(adjusted_pval, 2))%>% 
  select(type, pfas_name, `Odds Ratio[95%CI]`,`P-Value`, `P trend`,`Q trend`, term)%>%
  # pivot_wider(id_cols = c("pfas_name", "term"),
  #             names_from = "type",
  #             values_from = c(`Odds Ratio[95%CI]`, `P-Value`, `P trend`)) %>%
  mutate(term = paste(substr(term, (nchar(term)-8), nchar(term)-1) %>% toTitleCase(), substr(term, nchar(term), nchar(term)))) %>%
  mutate(across(everything(), ~ ifelse(. == "1 [NA, NA]", "1", .)))%>%
  mutate(pfas_name = rename_pfas(pfas_name)) %>%
  mutate(pfas_name = factor(pfas_name, levels = s0$pfas_name))%>%
  arrange(pfas_name)%>%
  select(pfas_name, term, everything())

writexl::write_xlsx(s2, fs::path(dir_result, "Supplemental Tables/Table S2. Dose response_Male.xlsx"))
```
