---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup prs and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```


## Analysis1: HCC
* All races
* Japanese American
* Latino
```{r interaction between PFAS and PRS}
# data_analysis_hcc4 <- data_hcc%>%
#   mutate_at(.vars = vars(paste0(pfas_name[1:length(pfas_name)], "_lg2")),
#             .funs = list(mean_centered = ~. -mean(., na.rm = TRUE))
#             ) 

covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
prs_name <- tibble(prs = "prs_uw_tertile")

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_names, prs_name, covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         exposure, "*", prs_name, 
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

## Analysis for all related participants
ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_hcc,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

## Analysis for Japanese American 
ind_vars$clogit_out1 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_hcc %>% filter(eth == "Japanese American"),
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

## Analysis for Latino
ind_vars$clogit_out2 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_hcc %>% filter(eth == "Latino"),
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>% 
  unnest(clogit_out1) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_latino <- ind_vars %>% 
  unnest(clogit_out2) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

```

### Fig 3a-1. Interaction between PFAS and PRS - All races
```{r interaction pfas and prs HCC, fig.height=8, fig.width= 10}
# add row for intercept (tertile 1)
interaction_term_name_ref <- paste0(pfas_name, ":", "prs_uw_tertile1")
intercept_data<- tibble(exposure = rep(pfas_name, 2), 
                        prs = rep("prs_uw_tertile", 2*length(pfas_name)), 
                        term = c(rep("prs_uw_tertile1", length(pfas_name)), interaction_term_name_ref), 
                        odds_ratio = rep(1,2*length(pfas_name)))



all_results_df_hcc1 <- all_results_df_hcc %>% bind_rows(intercept_data) %>% filter(grepl("lg2",term)|grepl("tertile", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(exposure = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and PRS",
                                 str_detect(term, "prs")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS and PRS"), 
         genetic_risk = case_when(str_detect(term, "tertile3") ~ "High", 
                                  str_detect(term, "tertile2") ~ "Medium",
                                  TRUE ~ "Low") |>
           fct_relevel(c("Low", "Medium", "High")), 
         sig = if_else(p.value < 0.05, "Sig.", "Not Sig.")) |>
  filter(!is.na(effect_type)) %>%
  mutate(color = case_when(p.value < 0.05 ~ "red", TRUE ~ "black"))

# Plot interaction effects
(pfas_grs_int <-  ggplot(all_results_df_hcc2 |> filter(str_detect(term, ":")),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("Interaction of PFAS and PRS") +
  scale_color_manual(values = c("black", "red")))


ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-1 Interaction of PFAS and PRS HCC.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")
# Plot pfas main effects
(pfas_int <-  ggplot(all_results_df_hcc2 |> filter(term %in% pfas_name),
       aes(x = reorder(exposure, odds_ratio), y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  # facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  coord_flip()+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.y=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    # ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("PFAS main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-1 PFAS PRS HCC_PFAS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot PRS effects
(grs_int <-  ggplot(all_results_df_hcc2 |> filter(effect_type == "Genetic Risk"),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) PRS") + 
      ggtitle("NAFLD PRS Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-1 PFAS PRS HCC_PRS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# cowplot::plot_grid(NULL, NULL, 
#                    grs_plot,
#                    pfos_grs_int, 
#                    nrow = 2, align = "h", 
#                     rel_heights = c(.05, 1),
#                    hjust = 0, #vjust = .99,
#                     
#                    labels = c("A. NAFLD PRS and HCC", 
#                               "B. PFOS and HCC by PRS"))
```

### Fig 3a-2. Interaction between PFAS and PRS - Japanese American
```{r interaction pfas and prs HCC Japan,fig.height=8, fig.width= 10}
# add row for intercept (tertile 1)
interaction_term_name_ref <- paste0(pfas_name, ":", "prs_uw_tertile1")
intercept_data<- tibble(exposure = rep(pfas_name, 2), 
                        prs = rep("prs_uw_tertile", 2*length(pfas_name)), 
                        term = c(rep("prs_uw_tertile1", length(pfas_name)), interaction_term_name_ref), 
                        odds_ratio = rep(1,2*length(pfas_name)))

all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% bind_rows(intercept_data) %>% filter(grepl("lg2",term)|grepl("tertile", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(exposure = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and PRS",
                                 str_detect(term, "prs")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS and PRS"), 
         genetic_risk = case_when(str_detect(term, "tertile3") ~ "High", 
                                  str_detect(term, "tertile2") ~ "Medium",
                                  TRUE ~ "Low") |>
           fct_relevel(c("Low", "Medium", "High")), 
         sig = if_else(p.value < 0.05, "Sig.", "Not Sig.")) |>
  filter(!is.na(effect_type)) %>%
  mutate(color = case_when(p.value < 0.05 ~ "red", TRUE ~ "black"))

# Plot interaction effects
(pfas_grs_int <-  ggplot(all_results_df_hcc_japan2 |> filter(str_detect(term, ":")),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("Interaction of PFAS and NAFLD PRS Tertile") +
  scale_color_manual(values = c("black", "red")))


ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-2 Interaction of PFAS and PRS HCC Japan.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot pfas main effects
(pfas_int <-  ggplot(all_results_df_hcc_japan2 |> filter(term %in% pfas_name),
       aes(x = reorder(exposure, odds_ratio), y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  # facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  coord_flip()+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    # ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("PFAS main effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-2 PFAS PRS HCC_PFAS main effect Japan.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot PRS effects
(grs_int <-  ggplot(all_results_df_hcc_japan2 |> filter(effect_type == "Genetic Risk"),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) PRS") + 
      ggtitle("NAFLD PRS Tertile Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-2 PFAS PRS HCC_PRS main effect Japan.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

```

### Fig 3a-3. Interaction between PFAS and PRS - Latino
```{r interaction pfas and prs HCC Latino,fig.height=8, fig.width= 10}
# add row for intercept (tertile 1)
interaction_term_name_ref <- paste0(pfas_name, ":", "prs_uw_tertile1")
intercept_data<- tibble(exposure = rep(pfas_name, 2), 
                        prs = rep("prs_uw_tertile", 2*length(pfas_name)), 
                        term = c(rep("prs_uw_tertile1", length(pfas_name)), interaction_term_name_ref), 
                        odds_ratio = rep(1,2*length(pfas_name)))


all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% bind_rows(intercept_data) %>% filter(grepl("lg2",term)|grepl("tertile", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(exposure = str_remove(exposure, "pfas_lg2_")) 


all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and PRS",
                                 str_detect(term, "prs")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS and PRS"), 
         genetic_risk = case_when(str_detect(term, "tertile3") ~ "High", 
                                  str_detect(term, "tertile2") ~ "Medium",
                                  TRUE ~ "Low") |>
           fct_relevel(c("Low", "Medium", "High")), 
         sig = if_else(p.value < 0.05, "Sig.", "Not Sig.")) |>
  filter(!is.na(effect_type)) %>%
  mutate(color = case_when(p.value < 0.05 ~ "red", TRUE ~ "black"))

# Plot interaction effects
(pfas_grs_int <-  ggplot(all_results_df_hcc_latino2 |> filter(str_detect(term, ":")),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x =element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("Interaction of PFAS and NAFLD PRS Tertile") +
  scale_color_manual(values = c("black", "red")))


ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-3 Interaction of PFAS and PRS HCC Latino.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")
# Plot pfas main effects
(pfas_int <-  ggplot(all_results_df_hcc_latino2 |> filter(term %in% pfas_name),
       aes(x = reorder(exposure, odds_ratio), y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  # facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  coord_flip()+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    # ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("PFAS Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-3 PFAS PRS HCC_PFAS main effect Latino.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot PRS effects
(grs_int <-  ggplot(all_results_df_hcc_latino2 |> filter(effect_type == "Genetic Risk"),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) PRS") + 
      ggtitle("NAFLD PRS Tertile Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3a-3 PFAS PRS HCC_PRS main effect Latino.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")
```

## Analysis2: NAFLD related HCC
```{r interaction between PFAS and PRS nafld related}
# data_analysis_nafld_hcc3 <- data_nafld_hcc%>%
#   mutate_at(.vars = vars(paste0(pfas_name[1:length(pfas_name)], "_lg2")),
#             .funs = list(mean_centered = ~. -mean(., na.rm = TRUE))
#             ) 

covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
prs_name <- tibble(prs = "prs_uw_tertile")

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_names, prs_name, covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         exposure, "*", prs_name, 
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

## Analysis for all related participants
ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_nafld_hcc,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

## Analysis for Japanese American 
ind_vars$clogit_out1 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_nafld_hcc %>% filter(eth == "Japanese American"),
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

## Analysis for Latino
ind_vars$clogit_out2 <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_nafld_hcc %>% filter(eth == "Latino"),
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

# Get final data -------------------
all_results_df_nafld_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_nafld_hcc_japan <- ind_vars %>% 
  unnest(clogit_out1) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_nafld_hcc_latino <- ind_vars %>% 
  unnest(clogit_out2) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))


```


### Fig3b-1. Interaction between PFAS and PRS All Races
```{r interaction nafld HCC,fig.height=8, fig.width= 10}
# add row for intercept (tertile 1)
interaction_term_name_ref <- paste0(pfas_name, ":", "prs_uw_tertile1")
intercept_data<- tibble(exposure = rep(pfas_name, 2), 
                        prs = rep("prs_uw_tertile", 2*length(pfas_name)), 
                        term = c(rep("prs_uw_tertile1", length(pfas_name)), interaction_term_name_ref), 
                        odds_ratio = rep(1,2*length(pfas_name)))

all_results_df_nafld_hcc1 <- all_results_df_nafld_hcc %>% bind_rows(intercept_data) %>% filter(grepl("lg2",term)|grepl("tertile", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(exposure = str_remove(exposure, "pfas_lg2_")) 


all_results_df_nafld_hcc2 <- all_results_df_nafld_hcc1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and PRS",
                                 str_detect(term, "prs")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS and PRS"), 
         genetic_risk = case_when(str_detect(term, "tertile3") ~ "High", 
                                  str_detect(term, "tertile2") ~ "Medium",
                                  TRUE ~ "Low") |>
           fct_relevel(c("Low", "Medium", "High")), 
         sig = if_else(p.value < 0.05, "Sig.", "Not Sig.")) |>
  filter(!is.na(effect_type)) %>%
  mutate(color = case_when(p.value < 0.05 ~ "red",
                      TRUE ~ "black"))
# Plot interaction effects
(pfas_grs_int <-  ggplot(all_results_df_nafld_hcc2 |> filter(str_detect(term, ":")),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("Interaction of PFAS and PRS") +
  scale_color_manual(values = c("black", "red")))


ggsave(filename = fs::path(dir_figures,
                           "Fig 3b-1 Interaction of PFAS and PRS NAFLD related HCC.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot pfas main effects
(pfas_int <-  ggplot(all_results_df_nafld_hcc2 |> filter(term %in% pfas_name),
       aes(x = reorder(exposure, odds_ratio), y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  # facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  coord_flip()+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    # ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("PFAS Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3b-1 PFAS PRS NAFLD related HCC_PFAS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot PRS effects
(grs_int <-  ggplot(all_results_df_nafld_hcc2 |> filter(effect_type == "Genetic Risk"),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) PRS") + 
      ggtitle("NAFLD PRS Tertile Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3b-1 PFAS PRS NAFLD related HCC_PRS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

```



## Analysis3: other HCC
```{r interaction between PFAS and PRS other related}
# data_analysis_other_hcc3 <- data_other_hcc%>%
#   mutate_at(.vars = vars(paste0(pfas_name[1:length(pfas_name)], "_lg2")),
#             .funs = list(mean_centered = ~. -mean(., na.rm = TRUE))
#             ) 

covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
prs_name <- tibble(prs = "prs_uw_tertile")

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_names, prs_name, covar_names) |>  
  mutate(formula = paste("status ~ v1 + v2 + v3 + v4 + v5 + v6 + ", 
                         exposure, "*", prs_name, 
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

## Analysis for all related participants
ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_other_hcc,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

## Analysis for Japanese American 
# ind_vars$clogit_out1 <- map(
#   ind_vars$formula, 
#   ~clogit(as.formula(.),
#           data = data_other_hcc %>% filter(eth == "Japanese American"),
#           method = "efron",
#           robust = TRUE
#   ) %>%
#     tidy(., conf.int = TRUE, level = 0.95) %>% 
#     mutate(
#       odds_ratio = exp(estimate),
#       exp_ci_low = exp(conf.low),
#       exp_ci_high = exp(conf.high),
#       model_type = "clogit")) 
# 
# ## Analysis for Latino
# ind_vars$clogit_out2 <- map(
#   ind_vars$formula, 
#   ~clogit(as.formula(.),
#           data = data_other_hcc %>% filter(eth == "Latino"),
#           method = "efron",
#           robust = TRUE
#   ) %>%
#     tidy(., conf.int = TRUE, level = 0.95) %>% 
#     mutate(
#       odds_ratio = exp(estimate),
#       exp_ci_low = exp(conf.low),
#       exp_ci_high = exp(conf.high),
#       model_type = "clogit")) 


# Get final data -------------------
all_results_df_other_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

# all_results_df_other_hcc_japan <- ind_vars %>% 
#   unnest(clogit_out1) %>% 
#   select(model_type, covariates, everything()) %>%
#   mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
#                          p.value >= 0.05 ~ "Not Sig"),
#          effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))
# 
# all_results_df_other_hcc_latino <- ind_vars %>% 
#   unnest(clogit_out2) %>% 
#   select(model_type, covariates, everything()) %>%
#   mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
#                          p.value >= 0.05 ~ "Not Sig"),
#          effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))
```

### Fig3c-1. Interaction between PFAS and PRS All Races
```{r interaction other HCC1,fig.height=8, fig.width= 10}
# add row for intercept (tertile 1)
interaction_term_name_ref <- paste0(pfas_name, ":", "prs_uw_tertile1")
intercept_data<- tibble(exposure = rep(pfas_name, 2), 
                        prs = rep("prs_uw_tertile", 2*length(pfas_name)), 
                        term = c(rep("prs_uw_tertile1", length(pfas_name)), interaction_term_name_ref), 
                        odds_ratio = rep(1,2*length(pfas_name)))

all_results_df_other_hcc1 <- all_results_df_other_hcc %>% bind_rows(intercept_data) %>% filter(grepl("lg2",term)|grepl("tertile", term)) %>%
  select(exposure, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(exposure = str_remove(exposure, "pfas_lg2_")) 


all_results_df_other_hcc2 <- all_results_df_other_hcc1 |> 
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and PRS",
                                 str_detect(term, "prs")   ~ "Genetic Risk",
                                 TRUE ~ "PFAS and PRS"), 
         genetic_risk = case_when(str_detect(term, "tertile3") ~ "High", 
                                  str_detect(term, "tertile2") ~ "Medium",
                                  TRUE ~ "Low") |>
           fct_relevel(c("Low", "Medium", "High")), 
         sig = if_else(p.value < 0.05, "Sig.", "Not Sig.")) |>
  filter(!is.na(effect_type)) %>%
  mutate(color = case_when(p.value < 0.05 ~ "red", TRUE ~ "black"))


# Plot interaction effects
(pfas_grs_int <-  ggplot(all_results_df_other_hcc2 |> filter(str_detect(term, ":")),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x = element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) per\ndoubling of PFAS") + 
    ggtitle("Interaction of PFAS and PRS") +
  scale_color_manual(values = c("black", "red")))


ggsave(filename = fs::path(dir_figures,
                           "Fig 3c-1 Interaction of PFAS and PRS other HCC.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot pfas main effects
(pfas_int <-  ggplot(all_results_df_other_hcc2 |> filter(term %in% pfas_name),
       aes(x = reorder(exposure, odds_ratio), y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  # facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  coord_flip()+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    # ylab("OR (95% CI) per\ndoubling of PFAS") + 
      ggtitle("PFAS Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3c-1 PFAS PRS other HCC_PFAS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")

# Plot PRS effects
(grs_int <-  ggplot(all_results_df_other_hcc2 |> filter(effect_type == "Genetic Risk"),
       aes(x = genetic_risk, y = odds_ratio, color = color)) +
  geom_errorbar(aes(ymin = exp_ci_low, ymax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_hline(yintercept = 1, linetype = 1, color = "grey50") +
  facet_wrap( ~ exposure, scales = "free", ncol = 6)+
  theme(#axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        legend.position = "none",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
    ylab("OR (95% CI) PRS") + 
      ggtitle("NAFLD PRS Tertile Main Effect") +
  scale_color_manual(values = c("black", "red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig 3c-1 PFAS PRS other HCC_PRS main effect.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")
```

