---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup univariate analysis cat pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))

diet <- haven::read_sas(fs::path(dir_data %>% dirname() %>% dirname() %>% dirname(),
                                             "0_data_processing",
                                             "0_raw_data",
                                             "diet_PRS_data",
                                             "pfas_food_diet.sas7bdat")) %>%
  janitor::clean_names()
```


# Analysis1. Meet in the middle - HCC
**Outcome: HCC vs control and PFAS**

**Exposure: Diet**

**Covars: sex, study location, ethnicity**

**Analysis: linear regression**

**Data Info: 237 cases, 237 controls**
## PFAS and Diet
```{r analysis1 diet and PFAS}
data_analysis_hcc_diet <- data_hcc %>% 
  mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
            .funs = list(scld = ~scale(.)))


pfas_diet <- epiomics::owas(data_analysis_hcc_diet, 
                            var = pfas_name,
                            omics = c(colnames(diet)[-1], "alcohol_intake"),
                            var_exposure_or_outcome = "outcome",
                            covars = covars_matched,
                            conf_int = TRUE) 

# reorder PFAS by estimate
pfas_diet1 <- pfas_diet |> 
  mutate(pfas_name = str_remove(var_name, "pfas_lg2_"),
         sig = case_when((p_value < 0.05 & adjusted_pval < 0.05) ~
                           "FDR p value < 0.05",
                          p_value < 0.05 ~ "p value < 0.05", 
                         p_value >= 0.05 ~ "p value ≥ 0.05"),
         sig = factor(sig, levels = c("p value ≥ 0.05", "p value < 0.05", "FDR p value < 0.05"))) 

```

## HCC and Diet
```{r analysis2 diet and hcc}
hcc_diet <- epiomics::owas_clogit(data_analysis_hcc_diet , 
                                    cc_set = "setnum", 
                                    cc_status = "status", 
                                    covars = NULL,
                                    omics = c(colnames(diet)[-1], "alcohol_intake"),
                                    conf_int = TRUE) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high))

# reorder PFAS by estimate
hcc_diet1 <- hcc_diet |> 
  mutate(sig = case_when((p_value < 0.05 & adjusted_pval < 0.05) ~
                           "FDR p value < 0.05",
                          p_value < 0.05 ~ "p value < 0.05", 
                         p_value >= 0.05 ~ "p value ≥ 0.05"),
         sig = factor(sig, levels = c("p value ≥ 0.05", "p value < 0.05", "FDR p value < 0.05")))
```

# Meet in the middle
```{r meet in the middle}
pfas_diet2 <- pfas_diet1 %>% filter(sig == "p value < 0.05")
hcc_diet2 <- hcc_diet1 %>% filter(sig == "p value < 0.05") 
```

### Fig1. association of pfas and diet, diet and hcc
```{r plot with covars only, fig.width=10, fig.height=5}
### Create metabolites Coefficient Plots
### Rename PFAS for plotting
pfas_diet3 <- pfas_diet2 %>%
  mutate(pfas_name = case_when(pfas_name == "4H_PFBA" ~ "4H-PFBA",
                               pfas_name == "10_2_FToH" ~ "10:2 FTOH",
                               pfas_name == "2_aminohexafluoropropan_2_ol" ~ "2-Aminohexafluoropropan-2-ol",
                               pfas_name == "Me_PFHxA" ~ "MePFHxA",
                               TRUE ~ pfas_name),
         ) 

(plot1 <- pfas_diet3  %>%
    # filter(feature_name %in% hcc_diet2$feature_name)%>%
  ggplot(aes(x = feature_name,y = exp(estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Overall \n(n = 474)", "Japanese American \n(n = 182)", "Latino \n(n = 160)", "Others \n(n = 132)")), scales = "free_y")+
  facet_wrap(.~ pfas_name, scales = "free", ncol = 3)+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank())+
  coord_flip() )

ggsave(filename = fs::path(dir_figures,
                           "Fig. diet and pfas full.jpeg"),
       width = 10,
       height = 7,
       dpi = 300,
       bg = "white")

(plot2 <- hcc_diet2  %>%
  ggplot(aes(x = feature_name,y = exp(estimate))) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  # facet_grid(.~ factor(type, levels = c("Overall \n(n = 474)", "Japanese American \n(n = 182)", "Latino \n(n = 160)", "Others \n(n = 132)")), scales = "free_y")+
  # facet_wrap(.~ pfas_name, scales = "free", ncol = 3)+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank())+
  coord_flip() )

ggsave(filename = fs::path(dir_figures,
                           "Fig. diet and hcc.jpeg"),
       width = 6,
       height = 4,
       dpi = 300,
       bg = "white")

# 
# writexl::write_xlsx(res_hcc2, fs::path(dir_result, "T1.Continuous PFAS and HCC.xlsx"))
```

# Logistic regression stratifying by high vs. low amds
```{r logistic regressionb stratified by high vs low amds}
data_hcc <- data_hcc%>%
  mutate(amds = ifelse(q1_dp_amds_e_totscore < quantile(q1_dp_amds_e_totscore, 0.5), 
                       "low", "high"))
data_hcc_low <- data_hcc %>% filter(amds == "low")
data_hcc_high <- data_hcc %>% filter(amds == "high")

res_hcc_low <- epiomics::owas(data_hcc_low, 
                              var = "status",
                              omics = pfas_name,
                              covars = covars_matched,
                              var_exposure_or_outcome = "outcome",
                              conf_int = TRUE,
                              ref_group = 0 ) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = "Low aMDS")

res_hcc_high <- epiomics::owas(data_hcc_high, 
                              var = "status",
                              omics = pfas_name,
                              covars = covars_matched,
                              var_exposure_or_outcome = "outcome",
                              conf_int = TRUE,
                              ref_group = 0 ) %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high),
         type = "High aMDS")

res_hcc <- res_hcc_low %>% bind_rows(res_hcc_high)

# eth_categories <- unique(data_hcc$eth_new)
# 
# for(race in eth_categories) {
#   res_hcc_temp <- epiomics::owas_clogit(data_hcc_low %>% filter(eth_new == race) , 
#                                     cc_set = "setnum", 
#                                     cc_status = "status", 
#                                     covars = covars,
#                                     omics = pfas_name,
#                                     conf_int = TRUE) %>%
#   mutate(odds_ratio = exp(estimate),
#          exp_ci_low = exp(conf_low),
#          exp_ci_high = exp(conf_high),
#          type = race)
#   res_hcc <- res_hcc %>% bind_rows(res_hcc_temp)
# }


# reorder PFAS by estimate
res_hcc1 <- res_hcc |> 
  mutate(pfas_name = str_remove(feature_name, "pfas_lg2_"),
         sig = case_when((p_value < 0.05 & adjusted_pval < 0.05) ~
                           "FDR p value < 0.05",
                          p_value < 0.05 ~ "p value < 0.05", 
                         p_value >= 0.05 ~ "p value ≥ 0.05"),
         sig = factor(sig, levels = c("p value ≥ 0.05", "p value < 0.05", "FDR p value < 0.05"))) 
# writexl::write_xlsx(all_results_df_hcc, fs::path(dir_result, "1_single_exposure_analysis_result_hcc.xlsx"))
```

### Fig1a. association of pfas and hcc - HCC
```{r plot with covars only, fig.width=10, fig.height=5}
### Create metabolites Coefficient Plots
### Rename PFAS for plotting
res_hcc2 <- res_hcc1 %>%
  mutate(pfas_name = case_when(pfas_name == "4H_PFBA" ~ "4H-PFBA",
                               pfas_name == "10_2_FToH" ~ "10:2 FTOH",
                               pfas_name == "2_aminohexafluoropropan_2_ol" ~ "2-Aminohexafluoropropan-2-ol",
                               pfas_name == "Me_PFHxA" ~ "MePFHxA",
                               TRUE ~ pfas_name),
         ) %>%
mutate(pfas_name = fct_reorder(pfas_name, if_else(type == "High aMDS", estimate, NA_real_)))
  # mutate(type = case_when(type == "Overall" ~ "Overall \n(n = 474)",
  #                         type == "Japanese American" ~ "Japanese American \n(n = 182)", 
  #                       type == "Latino"~ "Latino \n(n = 160)",
  #                       type == "Others" ~ "Others \n(n = 132)"))



(pfhpa_hcc_main <- res_hcc2  %>%
  ggplot(aes(x = pfas_name,y = exp(estimate), color = sig)) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = exp(conf_low),
                    ymax = exp(conf_high)),
                width = 0) +
  geom_hline(yintercept = 1, linetype = 2, color = "grey") +
  ylab("Odds Ratio (95% CI)") +
  # ggtitle("Exposure Outcome Analysis for HCC Cases") +
  facet_grid(.~ type, scales = "free_y")+
  theme(panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        # strip.text.x = element_blank(),
        text = element_text(size = 15),
        # axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.title.y=element_blank(),
        axis.line.y = element_line(color = "black"),
        legend.position = "bottom",
        legend.title = element_blank())+
  coord_flip() +
  scale_color_manual(values = c("grey","red","purple")))


ggsave(filename = fs::path(dir_figures,
                           "sensitivity",
                           "Fig PFAS and HCC stratified by aMDS.jpeg"),
       width = 10,
       height = 5,
       dpi = 300,
       bg = "white")
# 
# writexl::write_xlsx(res_hcc2, fs::path(dir_result, "T1.Continuous PFAS and HCC.xlsx"))
```
