---
title: 'MEC analysis'
subtitle: "Association of interactions between Diet and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup diet and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```

## Diet data Dictionary
```{r diet data dic}
data_dictionary <- labelled::generate_dictionary(diet)

data_dictionary %>% regulartable() %>% autofit() %>% 
  width(j=~pos, width=1) %>% 
  width(j=~variable,width=1) %>% 
  width(j=~label,width=3) %>%
  width(j=~col_type,width=1)

diet_info <- data.frame(diet_name = c("alcohol_intake_scld",
                                      "alcohol_intake_cat",
                                      "alcohol_intake_cat<12",
                                      "alcohol_intake_cat≥12",
                                      paste0(colnames(diet)[-1], "_scld")), 
                        new_name = c("Alcohol Intake",
                                     "Alcohol Intake (Categorical)",
                                     "Alcohol Intake <12", 
                                     "Alcohol Intake ≥12",
                                     "Popcorn",
                                     "Fish excluding shellfish",
                                     "Density of fish excluding shellfish",
                                     "Shellfish",
                                     "Density of shellfish",
                                     "Black Tea",
                                     "Green/Herbal Tea",
                                     "AHEI 2010 score",
                                     "AMDS",
                                     "Energy adjusted AMDS",
                                     "DASH score",
                                     "Energy adjusted DII q1",
                                     "HEI 2015 score",
                                     "edip",
                                     "edih",
                                     "edir",
                                     "elih",
                                     "elir") ) %>%
  mutate(new_name = factor(new_name, levels = c("Alcohol Intake", 
                                                "Alcohol Intake (Categorical)",
                                     "Alcohol Intake <12", 
                                     "Alcohol Intake ≥12",
                                     "Popcorn",
                                     "Fish excluding shellfish",
                                     "Density of fish excluding shellfish",
                                     "Shellfish",
                                     "Density of shellfish",
                                     "Black Tea",
                                     "Green/Herbal Tea",
                                     "AHEI 2010 score",
                                     "AMDS",
                                     "Energy adjusted AMDS",
                                     "DASH score",
                                     "Energy adjusted DII q1",
                                     "HEI 2015 score",
                                     "edip",
                                     "edih",
                                     "edir",
                                     "elih",
                                     "elir")))
```

## summary of diet
```{r summary of diet}
summarytools::view(summarytools::dfSummary(data_hcc %>%  select(colnames(diet)[-1], alcohol_intake),
                   style = 'grid',
                   max.distinct.values = 10, 
                   plain.ascii =   FALSE, 
                   valid.col = FALSE, 
                   headings = FALSE), method = "render")
```

## Summary of diet after categorized
```{r summary of diet after categorized}
new_name = c("diet_alcohol_intake",
                "diet_popcorn",
                "diet_fish_excluding_shellfish",
                "diet_density_of_fish_excluding_shellfish",
                "diet_shellfish",
                "diet_Density_of_shellfish",
                "diet_Black_Tea",
                "diet_Green_Tea_or_Herbal_Tea",
                "diet_AHEI_2010_score",
                "diet_AMDS",
                "diet_Energy_adjusted_AMDS",
                "diet_DASH_score",
                "diet_Energy_adjusted_DII_q1",
                "diet_HEI_2015_score",
                "diet_edip",
                "diet_edih",
                "diet_edir",
                "diet_elih",
                "diet_elir")

data_analysis_hcc_diet <- data_hcc %>% 
  mutate_at(.vars = c(colnames(diet)[c(-1, -7, -8)],"alcohol_intake"),
            .funs = list(median = ~ifelse(. < median(., na.rm = TRUE), "Low", "High") %>% factor(., levels = c("Low", "High"))))%>%
  mutate_at(.vars = c(colnames(diet)[c(7,8)]),
            .funs = list(median = ~ifelse(. < quantile(., 0.75), "Low", "High") %>% factor(., levels = c("Low", "High"))))

data.table::setnames(data_analysis_hcc_diet, 
         old = paste0(c("alcohol_intake", colnames(diet)[-1]), "_median"),
         new = new_name)
  
# data_analysis_nafld_hcc_diet <- data_nafld_hcc %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))
# 
# data_analysis_other_hcc_diet <- data_other_hcc %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))

data_analysis_hcc_japan_diet <- data_hcc %>%
  filter(eth == "Japanese American") %>%
  mutate_at(.vars = c(colnames(diet)[c(-1, -7, -8)],"alcohol_intake"),
            .funs = list(median = ~ifelse(. < median(., na.rm = TRUE), "Low", "High") %>% factor(., levels = c("Low", "High"))))%>%
  mutate_at(.vars = c(colnames(diet)[c(7,8)]),
            .funs = list(median = ~ifelse(. < quantile(., 0.75), "Low", "High") %>% factor(., levels = c("Low", "High"))))

data.table::setnames(data_analysis_hcc_japan_diet,
         old = paste0(c("alcohol_intake", colnames(diet)[-1]), "_median"),
         new = new_name)

# data_analysis_nafld_hcc_japan_diet <- data_nafld_hcc %>%
#   filter(eth == "Japanese American") %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))
#
# data_analysis_other_hcc_japan_diet <- data_other_hcc %>%
#   filter(eth == "Japanese American") %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))

data_analysis_hcc_latino_diet <- data_hcc %>%
  filter(eth == "Latino") %>%
  mutate_at(.vars = c(colnames(diet)[c(-1, -7, -8)],"alcohol_intake"),
            .funs = list(median = ~ifelse(. < median(., na.rm = TRUE), "Low", "High") %>% factor(., levels = c("Low", "High"))))%>%
  mutate_at(.vars = c(colnames(diet)[c(7,8)]),
            .funs = list(median = ~ifelse(. < quantile(., 0.75), "Low", "High") %>% factor(., levels = c("Low", "High"))))

data.table::setnames(data_analysis_hcc_latino_diet,
         old = paste0(c("alcohol_intake", colnames(diet)[-1]), "_median"),
         new = new_name)

# data_analysis_nafld_hcc_latino_diet <- data_nafld_hcc %>%
#   filter(eth == "Latino") %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))
#
# data_analysis_other_hcc_latino_diet <- data_other_hcc %>%
#   filter(eth == "Latino") %>%
#   mutate_at(.vars = c(colnames(diet)[-1],"alcohol_intake"),
#             .funs = list(scld = ~scale(.)))

summarytools::view(summarytools::dfSummary(data_analysis_hcc_diet %>%  select(new_name),
                   style = 'grid',
                   max.distinct.values = 10,
                   plain.ascii =   FALSE,
                   valid.col = FALSE,
                   headings = FALSE), method = "render")
```


## Analysis1: HCC
```{r interaction between PFAS and diet hcc}
covariate_input <- " scale(bmi) + diabetes + smokestatus"
## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
diet_name <- tibble(diet = new_name)

pfas_diet <- expand_grid(pfas_names, diet_name) %>%
  mutate(pfas_diet = paste(exposure,"*",diet)) 
  # %>%
  # group_by(exposure) %>%
  # summarise(pfas_diet_input = paste(pfas_diet, collapse = "+")) %>%
  # ungroup()

# Get Model covariates
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_diet,covar_names) |>
  mutate(formula = paste("status ~ ",
                         pfas_diet,
                         "+", covariates,
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_hcc_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

ind_vars$clogit_out1 <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_hcc_japan_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

ind_vars$clogit_out2 <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_hcc_latino_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

# Get final data -------------------
all_results_df_hcc <- ind_vars %>%
  unnest(clogit_out) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>%
  unnest(clogit_out1) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_latino <- ind_vars %>%
  unnest(clogit_out2) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("diet", term)|grepl("median", term)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 grepl("diet", term)   ~ "Diet",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type))


all_results_df_hcc3 <- all_results_df_hcc2 |>
  # tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
  
### Japanese American
all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% 
  # bind_rows(intercept_data) %>% 
 filter(grepl("lg2",term)|grepl("diet", term)|grepl("median", term)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))

all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 grepl("diet", term)   ~ "Diet",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type))


all_results_df_hcc_japan3 <- all_results_df_hcc_japan2 |>
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
  
## Latino 

all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|grepl("diet", term)|grepl("median", term)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 grepl("diet", term)   ~ "Diet",
                                 TRUE ~ "PFAS")) |>
  filter(!is.na(effect_type))


all_results_df_hcc_latino3 <- all_results_df_hcc_latino2 |>
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()

all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ "PFAS Main Effect",
                                effect_type == "Diet" ~ paste0(diet, "Main Effect"),
                                effect_type == "PFAS and Diet" ~ paste0(diet, "*PFAS Interaction")))
#   mutate(diet_type = ifelse(diet %in%
#                               c("alcohol_intake_cat<12","alcohol_intake_cat≥12"), 
#                             
# "alcohol_intake_cat", diet))
```

### Fig 5-1. Interaction of PFAS and Diet with HCC
```{r result diet hcc, fig.width= 15, fig.height=7}
  pfas = "Me_PFHxA"
  color_name = c("purple", "black","red")
  (plot <- all_result  %>% 
     filter(pfas_name == pfas) %>%
     ggplot(aes(x = name_plot, y = log(odds_ratio), color = sig)) +
  geom_errorbar(aes(ymin = log(exp_ci_low), ymax = log(exp_ci_high)),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) +
  geom_hline(yintercept = 0, linetype = 1, color = "grey50") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
        legend.position = "none",
        # panel.background = element_rect(fill="white"),
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        strip.text.x = element_blank(),
        text = element_text(size = 10),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
      ylab("Log OR (95% CI)") +
  ggtitle(paste0(pfas, " and Diet"))+
  scale_color_manual(values = color_name) +
  facet_grid(type ~ diet, scales = "free"))

  # ggsave(filename = fs::path(dir_figures,
  #                          paste0("Fig 5. ", pfas, " and Diet HCC.jpeg")),
  #      width = 17,
  #      height = 9,
  #      dpi = 300,
  #      bg = "white")
  

```


## Analysis2: NAFLD HCC
```{r interaction between PFAS and diet NAFLD hcc}

covariate_input <- " scale(bmi) + diabetes + smokestatus"
## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
diet_name <- tibble(diet = 
                      c("alcohol_intake_cat",
                        paste0(c("alcohol_intake",
                                 colnames(diet)[-1]), "_scld")) )

pfas_diet <- expand_grid(pfas_names, diet_name) %>%
  mutate(pfas_diet = paste(exposure,"*",diet)) 
  # %>%
  # group_by(exposure) %>%
  # summarise(pfas_diet_input = paste(pfas_diet, collapse = "+")) %>%
  # ungroup()

# Get Model covariates
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_diet,covar_names) |>
  mutate(formula = paste("status ~ ",
                         pfas_diet,
                         "+", covariates,
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_nafld_hcc_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

ind_vars$clogit_out1 <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_nafld_hcc_japan_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

# ind_vars$clogit_out2 <- map(
#   ind_vars$formula,
#   ~clogit(as.formula(.),
#           data = data_analysis_nafld_hcc_latino_diet,
#           method = "efron",
#           robust = TRUE
#   ) %>%
#     tidy(., conf.int = TRUE, level = 0.95) %>%
#     mutate(
#       odds_ratio = exp(estimate),
#       exp_ci_low = exp(conf.low),
#       exp_ci_high = exp(conf.high),
#       model_type = "clogit"))

# Get final data -------------------
all_results_df_hcc <- ind_vars %>%
  unnest(clogit_out) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>%
  unnest(clogit_out1) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

# all_results_df_hcc_latino <- ind_vars %>%
#   unnest(clogit_out2) %>%
#   select(model_type, covariates, everything()) %>%
#   mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 term %in% diet_info$diet_name   ~ "Diet",
                                 TRUE ~ "PFAS"),
         diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
                          term == "alcohol_intake_cat<12" ~
                            "alcohol_intake_cat<12",
                          term == "alcohol_intake_cat≥12" ~
                            "alcohol_intake_cat≥12",
                          TRUE ~ diet)) |>
  filter(!is.na(effect_type))


all_results_df_hcc3 <- all_results_df_hcc2 |>
  tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
  
### Japanese American
all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
  select(exposure,diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 term %in% diet_info$diet_name   ~ "Diet",
                                 TRUE ~ "PFAS"),
         diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
                          term == "alcohol_intake_cat<12" ~
                            "alcohol_intake_cat<12",
                          term == "alcohol_intake_cat≥12" ~
                            "alcohol_intake_cat≥12",
                          TRUE ~ diet)) |>
  filter(!is.na(effect_type))


all_results_df_hcc_japan3 <- all_results_df_hcc_japan2 |>
  tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
## Latino 

# all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% 
#   # bind_rows(intercept_data) %>% 
#   filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
#   select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
#   mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))
# 
# 
# all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |>
#   mutate(
#          effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
#                                  term %in% diet_info$diet_name   ~ "Diet",
#                                  TRUE ~ "PFAS"),
#          diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
#                           term == "alcohol_intake_cat<12" ~
#                             "alcohol_intake_cat<12",
#                           term == "alcohol_intake_cat≥12" ~
#                             "alcohol_intake_cat≥12",
#                           TRUE ~ diet)) |>
#   filter(!is.na(effect_type))
# 
# 
# all_results_df_hcc_latino3 <- all_results_df_hcc_latino2 |>
#   tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
#   group_by(pfas_name) %>%
#   mutate(
#     # diet = str_replace_all(diet, "_scld", "")%>%str_replace_all("q1_", "") ,
#          p_adjusted = p.adjust(p.value, method = "fdr"),
#          sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
#                          p.value < 0.05 ~ "Sig.",
#                          TRUE ~ "Not Sig.")) %>%
#   ungroup()


all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  # bind_rows(all_results_df_hcc_latino3 %>%
  #             mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ "PFAS Main Effect",
                                effect_type == "Diet" ~ paste0(new_name, "Main Effect"),
                                effect_type == "PFAS and Diet" ~ paste0(new_name, "*PFAS Interaction")))%>%
  mutate(diet_type = ifelse(diet %in%
                              c("alcohol_intake_cat<12","alcohol_intake_cat≥12"), 
                            
"alcohol_intake_cat", diet))
```

### Fig 5-2. Interaction of PFAS and Diet with NAFLD related HCC
```{r result diet nafld hcc, fig.width= 15, fig.height=7}
for (pfas in c("PFHpA", unique(all_result$pfas_name)[-8])){
  if(pfas %in% c(unique(all_result$pfas_name)[c(1,4,11,13,15,16,17)])){
    color_name = c("black","red")
  }else{
    color_name = c("purple", "black","red")
  }
  (plot <- all_result  %>% 
     filter(pfas_name == pfas) %>%
     ggplot(aes(x = name_plot, y = log(odds_ratio), color = sig)) +
  geom_errorbar(aes(ymin = log(exp_ci_low), ymax = log(exp_ci_high)),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) +
  geom_hline(yintercept = 0, linetype = 1, color = "grey50") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
        legend.position = "none",
        # panel.background = element_rect(fill="white"),
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        strip.text.x = element_blank(),
        text = element_text(size = 10),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
      ylab("Log OR (95% CI)") +
  ggtitle(paste0(pfas, " and Diet"))+
  scale_color_manual(values = color_name) +
  facet_grid(type ~ diet_type, scales = "free"))

  ggsave(filename = fs::path(dir_figures,
                           paste0("Fig 5. ", pfas, " and Diet NAFLD HCC.jpeg")),
       width = 17,
       height = 9,
       dpi = 300,
       bg = "white")
  
  print(plot)
}

```

## Analysis3: Other HCC
```{r interaction between PFAS and diet other hcc}

covariate_input <- " scale(bmi) + diabetes + smokestatus"
## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
diet_name <- tibble(diet = 
                      c("alcohol_intake_cat",
                        paste0(c("alcohol_intake",
                                 colnames(diet)[-1]), "_scld")) )

pfas_diet <- expand_grid(pfas_names, diet_name) %>%
  mutate(pfas_diet = paste(exposure,"*",diet)) 
  # %>%
  # group_by(exposure) %>%
  # summarise(pfas_diet_input = paste(pfas_diet, collapse = "+")) %>%
  # ungroup()

# Get Model covariates
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_diet,covar_names) |>
  mutate(formula = paste("status ~ ",
                         pfas_diet,
                         "+", covariates,
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

ind_vars$clogit_out <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_other_hcc_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

ind_vars$clogit_out1 <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_other_hcc_japan_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

ind_vars$clogit_out2 <- map(
  ind_vars$formula,
  ~clogit(as.formula(.),
          data = data_analysis_other_hcc_latino_diet,
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>%
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit"))

# Get final data -------------------
all_results_df_hcc <- ind_vars %>%
  unnest(clogit_out) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_japan <- ind_vars %>%
  unnest(clogit_out1) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

all_results_df_hcc_latino <- ind_vars %>%
  unnest(clogit_out2) %>%
  select(model_type, covariates, everything()) %>%
  mutate(effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

## Adding modify variable names, add type or category info for data-----

### All races
all_results_df_hcc1 <- all_results_df_hcc %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc2 <- all_results_df_hcc1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 term %in% diet_info$diet_name   ~ "Diet",
                                 TRUE ~ "PFAS"),
         diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
                          term == "alcohol_intake_cat<12" ~
                            "alcohol_intake_cat<12",
                          term == "alcohol_intake_cat≥12" ~
                            "alcohol_intake_cat≥12",
                          TRUE ~ diet)) |>
  filter(!is.na(effect_type))


all_results_df_hcc3 <- all_results_df_hcc2 |>
  tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
  
### Japanese American
all_results_df_hcc_japan1 <- all_results_df_hcc_japan %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
  select(exposure,diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_japan2 <- all_results_df_hcc_japan1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 term %in% diet_info$diet_name   ~ "Diet",
                                 TRUE ~ "PFAS"),
         diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
                          term == "alcohol_intake_cat<12" ~
                            "alcohol_intake_cat<12",
                          term == "alcohol_intake_cat≥12" ~
                            "alcohol_intake_cat≥12",
                          TRUE ~ diet)) |>
  filter(!is.na(effect_type))


all_results_df_hcc_japan3 <- all_results_df_hcc_japan2 |>
  tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()
## Latino 

all_results_df_hcc_latino1 <- all_results_df_hcc_latino %>% 
  # bind_rows(intercept_data) %>% 
  filter(grepl("lg2",term)|(term %in% diet_info$diet_name)) %>%
  select(exposure, diet, term, p.value, odds_ratio, contains("exp_")) %>%
  mutate(pfas_name = str_remove(exposure, "pfas_lg2_"))


all_results_df_hcc_latino2 <- all_results_df_hcc_latino1 |>
  mutate(
         effect_type = case_when(str_detect(term, ":")   ~ "PFAS and Diet",
                                 term %in% diet_info$diet_name   ~ "Diet",
                                 TRUE ~ "PFAS"),
         diet = case_when(diet == "alcohol_intake_cat"&grepl(":", term) ~ str_split_fixed(term, ":", 2)[,2], 
                          term == "alcohol_intake_cat<12" ~
                            "alcohol_intake_cat<12",
                          term == "alcohol_intake_cat≥12" ~
                            "alcohol_intake_cat≥12",
                          TRUE ~ diet)) |>
  filter(!is.na(effect_type))


all_results_df_hcc_latino3 <- all_results_df_hcc_latino2 |>
  tidylog::left_join(diet_info, by = c("diet" = "diet_name")) %>%
  group_by(pfas_name) %>%
  mutate(
    # diet = str_replace_all(diet, "_scld", "")%>%str_replace_all("q1_", "") ,
         p_adjusted = p.adjust(p.value, method = "fdr"),
         sig = case_when(p_adjusted < 0.05 ~ "FDR. Sig.", 
                         p.value < 0.05 ~ "Sig.",
                         TRUE ~ "Not Sig.")) %>%
  ungroup()


all_result <- all_results_df_hcc3 %>%
  mutate(type = "All races") %>%
  bind_rows(all_results_df_hcc_japan3 %>% 
              mutate (type = "Japanese American")) %>%
  bind_rows(all_results_df_hcc_latino3 %>%
              mutate (type = "Latino"))%>%
  mutate(name_plot  = case_when(effect_type == "PFAS" ~ "PFAS Main Effect",
                                effect_type == "Diet" ~ paste0(new_name, "Main Effect"),
                                effect_type == "PFAS and Diet" ~ paste0(new_name, "*PFAS Interaction")))%>%
  mutate(diet_type = ifelse(diet %in%
                              c("alcohol_intake_cat<12","alcohol_intake_cat≥12"), 
                            "alcohol_intake_cat", diet))
```

### Fig 5-3. Interaction of PFAS and Diet with other HCC
```{r result diet other hcc, fig.width= 15, fig.height=7}
for (pfas in c("PFHpA", unique(all_result$pfas_name)[-8])){
  if(pfas %in% c(unique(all_result$pfas_name)[c(3,5,10,16,17)])){
    color_name = c("black","red")
  }else{
    color_name = c("purple", "black","red")
  }
  (plot <- all_result  %>% 
     filter(pfas_name == pfas) %>%
     ggplot(aes(x = name_plot, y = log(odds_ratio), color = sig)) +
  geom_errorbar(aes(ymin = log(exp_ci_low), ymax = log(exp_ci_high)),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) +
  geom_hline(yintercept = 0, linetype = 1, color = "grey50") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
        legend.position = "none",
        # panel.background = element_rect(fill="white"),
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        strip.text.x = element_blank(),
        text = element_text(size = 10),
        axis.title.x=element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
      ylab("Log OR (95% CI)") +
  ggtitle(paste0(pfas, " and Diet"))+
  scale_color_manual(values = color_name) +
  facet_grid(type ~ diet_type, scales = "free"))

  ggsave(filename = fs::path(dir_figures,
                           paste0("Fig 5. ", pfas, " and Diet Other HCC.jpeg")),
       width = 17,
       height = 9,
       dpi = 300,
       bg = "white")
  
  print(plot)
}

```
