---
title: 'MEC analysis'
subtitle: "Association of interactions between SNPs and PFAS with HCC"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup snp and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```


## Gam Models Functions
```{r}
#adjusted gam model that is log2 transformed exposure 
model_output_gam_log <- function(eo_combinations,df){
  # Create regression model formula
  models <- eo_combinations %>%
    mutate(
      covars = str_c(covars_matched,collapse = "+"),
      formula = str_c(y,"~","s(","log2(","`", x,"`" , ")",")", "+", covars))
  # Run GAM models
  models$output <- map(models$formula,
                       ~mgcv::gam(as.formula(.),
                            data = df,
                            na.action = na.exclude,
                            family = binomial
                       )%>%
                         tidy(., conf.int = FALSE))
  
  models$mod <- map(models$formula,
                    ~mgcv::gam(as.formula(.),
                         data = df,
                         na.action = na.exclude,
                         family = binomial
                    ))
  return(models)
}

#GAM model with covariates no log transformation includes spline (logistic)
model_output_gam <- function(eo_combinations,df){
  # Create regression model formula
  models <- eo_combinations %>%
    mutate(
      covars = str_c(covars_matched,collapse = "+"),
      formula = str_c(y,"~","s(",  "`", x,"`",")", "+", covars))
  # Run GAM models
  models$output <- map(models$formula,
                       ~mgcv::gam(as.formula(.),
                            data = df,
                            na.action = na.exclude,
                            family = binomial
                       )%>%
                         tidy(., conf.int = FALSE))
  
  models$mod <- map(models$formula,
                    ~mgcv::gam(as.formula(.),
                         data = df,
                         na.action = na.exclude,
                         family = binomial
                    ))
  return(models)
}

#GAM model with covariates no log -- no spline (logistic)
model_output_gam_linear <- function(eo_combinations,df){
  # Create regression model formula
  models <- eo_combinations %>%
    mutate(
      covars = str_c(covars_matched,collapse = "+"),
      formula = str_c(y,"~", "`", x,"`", "+", covars))
  # Run GAM models
  models$output <- map(models$formula,
                       ~glm(as.formula(.),
                            data = df,
                            na.action = na.exclude,
                            family = binomial
                       )%>%
                         tidy(., conf.int = TRUE))
  
  models$mod <- map(models$formula,
                    ~mgcv::gam(as.formula(.),
                         data = df,
                         na.action = na.exclude,
                         family = binomial
                    ))
  return(models)
}

#log transformed GAM model (adjusted) no spline
model_output_gam_linear_log <- function(eo_combinations,df){
  # Create regression model formula
  models <- eo_combinations %>%
    mutate(
      covars = str_c(covars_matched,collapse = "+"),
      formula = str_c(y,"~","log2(", "`", x,"`", ")", "+", covars))
  # Run GAM models
  models$output <- map(models$formula,
                       ~glm(as.formula(.),
                            data = df,
                            na.action = na.exclude,
                            family = binomial
                       )%>%
                         tidy(., conf.int = TRUE))
  
  models$mod <- map(models$formula,
                    ~mgcv::gam(as.formula(.),
                         data = df,
                         na.action = na.exclude,
                         family = binomial
                    ))
  return(models)
}

```

## Run Models
```{r}
covars_matched <- c("eth","studyarea","q1_age_cohent")
data_analysis <- data_hcc %>%
  rename_at(.vars = c(pfas_name_raw),
            .funs = ~str_remove(., "_raw"))%>%
  # filter(sex == "Male")
  filter(sex == "Female")

pfas_name_new <- str_remove(pfas_name_raw, "_raw")

eo_combinations<- list(x = pfas_name_new ,
                       y = "status") %>%
  cross_df()
##### Spline Model #####
# Original model(without log transform)
# Model: nafld(Y/N) ~ s(Raw plasma pfas(continuous)) + covars
models_spline <- model_output_gam(eo_combinations, data_analysis)

mod_output_df <- models_spline %>%
  unnest(output)

# write_csv(mod_output_df,fs::path(dir_report,
#                                  "GAM_nafld_pfas.csv"),
#           col_names = TRUE)

##### linear piece #####
# model: nafld(Y/N) ~ Raw plasma pfas(continuous) + covars
models_linear <- model_output_gam_linear(eo_combinations, data_analysis)

mod_output_df <- models_linear %>%
  unnest(output)

# write_csv(mod_output_df,fs::path(dir_report,
#                                  "GAM_nafld_pfas_linear.csv"),
#           col_names = TRUE)

## Anova test
result <- map2(.x = models_linear$mod, .y = models_spline$mod, 
               ~anova(.x, .y, test = "Chisq") %>% tidy(.)) 

names(result) <- models_spline$x
result1 <- result %>% bind_rows(.id = "pfas")
result2 <- result1 %>% 
  mutate(p.value = ifelse(deviance < 0.001, 1, p.value),
         Deviance = ifelse(deviance < 0.001, 0, deviance),
         df = ifelse(df < 0.001, 0, df))

write_csv(result2,fs::path(dir_result,
                                 "GAM_spline and liner comparison_female.csv"),
          col_names = TRUE)

####### Spline Model #######
# log transform for exposures
# model: nafld(Y/N) ~ s(log2(Imputed plasma pfas(continuous))) + covars
models_spline_log <- model_output_gam_log(eo_combinations, data_analysis)

mod_output_df <- models_spline_log %>%
  unnest(output)

# write_csv(mod_output_df,fs::path(dir_report,
#                                  "GAM_nafld_pfas_log.csv"),
#           col_names = TRUE)

# model: nafld(Y/N) ~ log2(Imputed plasma pfas(continuous)) + covars
models_linear_log <- model_output_gam_linear_log(eo_combinations, data_analysis)

mod_output_df <- models_linear_log %>%
  unnest(output)

# write_csv(mod_output_df,fs::path(dir_report,
#                                  "GAM_nafld_pfas_linear_log.csv"),
#           col_names = TRUE)

## anova test
result <- map2(.x = models_linear_log$mod, .y = models_spline_log$mod, 
               ~anova(.x, .y, test = "Chisq") %>% tidy(.)) 
names(result) <- models_spline_log$x
result1 <- result %>% bind_rows(.id = "pfas")
result2 <- result1 %>% 
  mutate(p.value = ifelse(deviance < 0.001, 1, p.value),
         Deviance = ifelse(deviance < 0.001, 0, deviance),
         df = ifelse(df < 0.001, 0, df))

write_csv(result2,fs::path(dir_result,
                           "GAM_spline and liner comparison log_female.csv"),
          col_names = TRUE)



# plot result for each pfas
for(i in 1:length(pfas_name_new)){
  name <- colnames(models_spline$mod[[i]]$model)[5]
  png(fs::path(dir_figures, "GAM", paste0("GAM_spline_",name, "_female.png")),
      width = 2000, height = 1000)
    par(mfrow = c(1,2), mar=c(5,6,4,2))
    plot(models_spline$mod[[i]],cex.axis = 2.5, cex.lab = 2.5)
    plot(models_spline_log$mod[[i]], cex.axis = 2.5, cex.lab = 2.5)
dev.off()
}

```

