---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup prs and pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```


## Analysis1: HCC
* All races
* Japanese American
* Latino
```{r interaction between PFAS and Races}
# data_analysis_hcc4 <- data_hcc%>%
#   mutate_at(.vars = vars(paste0(pfas_name[1:length(pfas_name)], "_lg2")),
#             .funs = list(mean_centered = ~. -mean(., na.rm = TRUE))
#             ) 

covariate_input <- " alcohol_intake + scale(bmi) + diabetes + smokestatus" 

## create dataframe with names of dependent vars (PFAS) ----
pfas_names <- tibble(exposure = pfas_name)

## create dataframe with names of PRS vars ----
race_name <- tibble(race_var = "eth")

# Get Model covariates 
covar_names <- tibble(
  covariates =  covariate_input)

# Make all clogit formulas
ind_vars <- expand_grid(pfas_names, race_name, covar_names) |>  
  mutate(formula = paste("status ~ ", 
                         exposure, "*", race_name, 
                         "+", covariates, 
                         "+strata(setnum)") |>
           str_replace("\\+  \\+", " + "))

## Analysis for all related participants
ind_vars$clogit_out <- map(
  ind_vars$formula, 
  ~clogit(as.formula(.),
          data = data_other_hcc
          # %>% mutate(eth = factor(eth, levels = c("Japanese American", "White", "African American", "Latino", "Native Hawaiian"))),
          %>%
            mutate(eth = case_when(eth == "Japanese American" ~ "Japanese American",
                                   eth == "Latino" ~ "Latino",
                                   TRUE ~ "Others")),
          method = "efron",
          robust = TRUE
  ) %>%
    tidy(., conf.int = TRUE, level = 0.95) %>% 
    mutate(
      odds_ratio = exp(estimate),
      exp_ci_low = exp(conf.low),
      exp_ci_high = exp(conf.high),
      model_type = "clogit")) 

# Get final data -------------------
all_results_df_hcc <- ind_vars %>% 
  unnest(clogit_out) %>% 
  select(model_type, covariates, everything()) %>%
  mutate(sig = case_when(p.value < 0.05 ~ "Sig", 
                         p.value >= 0.05 ~ "Not Sig"),
         effect_est = jag2::effest_ci(odds_ratio, exp_ci_low, exp_ci_high))

pfhpa_df_hcc <- all_results_df_hcc %>% filter(grepl("PFHpA",exposure)) %>% filter(grepl(":",term))
pfhpa_df_nafld_hcc <- all_results_df_hcc %>% filter(grepl("PFHpA",exposure)) %>% filter(grepl(":",term))
pfhpa_df_other_hcc <- all_results_df_hcc %>% filter(grepl("PFHpA",exposure)) %>% filter(grepl(":",term))

pfhpa_df <- pfhpa_df_hcc %>% mutate(type = "HCC") %>%
  bind_rows(pfhpa_df_nafld_hcc %>% mutate(type = "NAFLD Related HCC")) %>%
  bind_rows(pfhpa_df_other_hcc %>% mutate(type = "NAFLD Other HCC"))

writexl::write_xlsx(pfhpa_df, fs::path(dir_result, "interaction of pfas and race.xlsx"))
```

