---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
source(fs::path(here::here("functions.R")))
```

# 0. Load Data and data processing
```{r child = "0_0 Descriptive.Rmd"}

```

# 1. Single Exposure Analysis - Continuous PFAS
```{r child="0_1 Single Exposure Analysis.Rmd"}

```

# 2. Single Exposure Analysis - Categorized PFAS
```{r child="0_1 Single Categorical Exposure Analysis.Rmd"}

```

# 2. Genetic risk score(PRS) for NAFLD is associated with HCC
```{r child= "0_2 Association of PRS and HCC.Rmd"}

```

# 3. Association of interaction between PFAS and PRS with HCC
```{r child= "0_3 Interaction between PRS and PFAS.Rmd"}

```

# 4. Association of interaction between PFAS and SNPs with HCC
```{r child= "0_4 Interaction between SNPs and PFAS.Rmd"}

```

# 5. Association of interaction between PFAS and Diet with HCC
```{r child= "0_5 Interaction between Diet and PFAS.Rmd"}

```

