---
title: 'MEC analysis'
subtitle: "Final Analysis"
author: "Hongxu Wang, Jesse Goodrich"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup univariate analysis cat pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("1_Project_Setup/!libraries.R")))
source(fs::path(here::here("1_Project_Setup/!directories.R")))
source(fs::path(here::here("1_Project_Setup/!functions.R")))
source(fs::path(here::here("1_Project_Setup/!load_data.R")))

```

## Descriptive
```{r}
data_hcc %>% select(blood_age, status, eth, bmi_cat, alcohol_intake_cat, smokestatus, diabetes, studyarea, sex, year_between,smokestatus_imputed, q1_d_chol, q1_elih_imputed, q1_edih, prs_wt, prs_wt_std) %>%
  tbl_summary(by = status,
              type = all_continuous() ~ "continuous2",
              statistic = list(
                               all_continuous() ~ c("{mean} ({sd})",
                                                    "{median} ({p25}, {p75})"),
                               all_categorical() ~ "{n} ({p}%)")) %>%
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n()
```

## Check for missing PFAS values and rerun descriptive statistics using the complete PFAS data
* Complete PFAS means both control and case (same setnum) have PFAS values
```{r}
data_pfas_missing <- data_hcc %>% filter(is.na(pfas_t_PFDA))
data_hcc_c <- data_hcc %>% filter(!setnum %in% data_pfas_missing$setnum)
table(data_hcc_c$eth)

data_hcc_c %>% select(blood_age, status, eth, bmi_cat, alcohol_intake_cat, smokestatus, diabetes, studyarea, sex, year_between,smokestatus_imputed, q1_d_chol, q1_elih_imputed, q1_edih, prs_wt, prs_wt_std) %>%
  tbl_summary(by = status,
              type = all_continuous() ~ "continuous2",
              statistic = list(
                               all_continuous() ~ c("{mean} ({sd})",
                                                    "{median} ({p25}, {p75})"),
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(
                all_continuous() ~ 1, 
                all_categorical() ~ c(1, 1))) %>%
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n()

# Data with complete genetic data based on data with complete PFAS data (data_hcc_c)
data_gene_missing <- data_hcc_c %>% filter(is.na(prs_wt))
data_hcc_c_gene <- data_hcc_c %>% filter(!setnum %in% data_gene_missing$setnum)


data_hcc_c_gene %>% select(blood_age, status, eth, bmi_cat, alcohol_intake_cat, smokestatus, diabetes, studyarea, sex, year_between,smokestatus_imputed, q1_d_chol, q1_elih_imputed, q1_edih, prs_wt, prs_wt_std) %>%
  tbl_summary(by = status,
              type = all_continuous() ~ "continuous2",
              statistic = list(
                               all_continuous() ~ c("{mean} ({sd})",
                                                    "{median} ({p25}, {p75})"),
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(
                all_continuous() ~ 1, 
                all_categorical() ~ c(1, 1))) %>%
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n()

# data_hcc_c_gene %>% select(prs_wt, eth, status) %>%
#   mutate(status_eth = paste(status, eth, sep = "_")) %>%
#   tbl_summary(by = status_eth,
#               type = all_continuous() ~ "continuous2",
#               statistic = list(
#                                all_continuous() ~ c("{mean} ({sd})",
#                                                     "{median} ({p25}, {p75})"),
#                                all_categorical() ~ "{n} ({p}%)"),
#               digits = list(
#                 all_continuous() ~ 1, 
#                 all_categorical() ~ c(1, 1))) %>%
#   add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
#   add_overall() %>%
#   add_n()

# Revision1. Add the PRS values and the corresponding p-values comparing cases and controls, both overall and stratified by race

data_hcc_c_gene %>%
  select(prs_wt, eth, status) %>%
  tbl_strata(
    strata = eth,
    .tbl_fun = ~ .x %>%
      tbl_summary(
        by = status,
        type = all_continuous() ~ "continuous2",
        statistic = all_continuous() ~ c(
          "{mean} ({sd})",
          "{median} ({p25}, {p75})"
        )
      ) %>%
      add_p())


data_hcc %>%
  filter(status == 0) %>%
  select(prs_wt_median, eth) %>%
  tbl_summary(
    by = eth,
    type = prs_wt_median ~ "categorical",
    statistic = prs_wt_median ~ "{n} ({p}%)"
  ) %>%
  add_p()

(data_hcc_c_gene%>%
  filter(status == 0) %>%
  select(prs_wt_median, eth) %>%
  tbl_summary(
    by = eth,
    type = prs_wt_median ~ "categorical",
    statistic = prs_wt_median ~ "{n} ({p}%)"
  ) %>%
  add_p())

# (data %>%
#   filter(status == "Control") %>%
#   select(prs_wt_median, eth) %>%
#   tbl_summary(
#     by = eth,
#     type = prs_wt_median ~ "categorical",
#     statistic = prs_wt_median ~ "{n} ({p}%)"
#   ) %>%
#   add_p())


rm(data_hcc_c)
```

## Correlation of PFAS(raw)
```{r correlation of PFAS}
sample_id1 <- data %>% filter(status == "HCC") %>% 
  dplyr::select(setnum)

data_hcc_raw <- data %>% filter(setnum %in% sample_id1$setnum) %>%
  mutate(status = ifelse(status == "HCC", 1, 0))%>%
  filter(!setnum %in% data_pfas_missing$setnum) %>% 
  filter(sid %in% data_hcc_c_gene$sid)
  
pfas_mat_for_cor <- data_hcc_raw %>% 
  dplyr::select(all_of(pfas_name[-13]))%>%
  as.data.frame()

# Run Correlation Matrix
cor_matrix <- polycor::hetcor(pfas_mat_for_cor)
cor_matrix$spearman <- cor(pfas_mat_for_cor, method = "spearman")

# Get correlation Matrix and  pivot longer
cor_matrix_df_1 <- as_tibble(cor_matrix$spearman) %>% 
  mutate(pfas= names(cor_matrix$correlations[,1])) %>% 
  select(pfas, everything()) 

# Pivot longer
cor_matrix_df_1 <- cor_matrix_df_1 %>% 
  pivot_longer(names_to = "pfas_2",
               values_to = "correlation",
               cols = colnames(cor_matrix_df_1)[-1])

# Get correlation method
cor_method_df_1 <- as_tibble(cor_matrix$type) %>% mutate(across(everything(), 
                                                                              ~str_replace(., "Pearson", "Spearman")))

colnames(cor_method_df_1) <- names(cor_matrix$correlations[,1])

# Pivot longer
cor_method_df_2 <- cor_method_df_1 %>% 
  mutate(pfas = names(cor_matrix$spearman[,1])) %>% 
  select(pfas, everything()) %>% 
  pivot_longer(., 
               names_to = "pfas_2",
               values_to = "method",
               cols = names(cor_matrix$spearman[,1]))

# Combine p values and method
cor_matrix_df_2 <- left_join(cor_matrix_df_1, 
                                   cor_method_df_2)

# Calculate p-values 
cor_matrix_df_2 <- cor_matrix_df_2 %>% 
  rowwise() %>% 
  mutate(p = cor_to_p(cor = correlation, 
                      n = length(unique(data_hcc$sid)), 
                      method = method)$p) %>% 
  as_tibble()


# Relevel factors (This gives a warning because we dont include PFHxA in analysis (100% < LOD)
cor_matrix_df_3 <- cor_matrix_df_2 %>%
  mutate(pfas_names_1 = rename_pfas(pfas), 
         pfas_names_2 = rename_pfas(pfas_2))

## Reorder cor matrix for fig ----------------
cor_matrix_df_4 <- cor_matrix_df_3 %>% 
  # left_join(lod, by = "pfas") %>% 
  arrange(pfas_names_1, pfas_names_2) %>%
  group_by(pfas_names_1) %>% 
  mutate(group_1 = row_number()) %>% 
  ungroup() %>%
  group_by(pfas_names_2) %>% 
  mutate(group_2 = row_number()) %>% 
  ungroup() %>% 
  mutate(correlation_2 = if_else(group_2 <= group_1, 0, correlation),
         p_2 = if_else(group_2 <= group_1, NA_real_, p) %>% 
           p.adjust(., method = "fdr"),
         sig = if_else(p_2 < 0.05, "*", "") %>% 
           if_else(group_2 <= group_1, "", .), 
         correlation_3 = 
           if_else(group_2 <= group_1, 
                   "", 
                   str_c(formatC(correlation, format = "f", digits = 2), 
                         sig)))


## Plot legacy Correlation Plot ----------------
(corplot <- cor_matrix_df_4 %>% ggplot(aes(x = pfas_names_1, 
                             y = pfas_names_2, 
                             fill = correlation_2, 
                             label = correlation_3)) + 
   geom_tile(color = "white") + 
   geom_text() + 
   scale_fill_gradient2(limit = c(-1,1), 
                        low = "blue", 
                        high =  "red", 
                        mid = "white",
                        midpoint = 0, 
                        name= "Spearman\nCorrelation\nCoefficient") + 
   ggthemes::theme_tufte(base_size = 17) +
   theme(axis.text.x = element_text(angle = 45, hjust = 1), 
         axis.title.x = element_blank(), 
         axis.title.y = element_blank()))

# Get info about correlation structure 
cor_matrix_df_4 %>% 
  filter(method != "", 
         correlation_2 != 0) %>% 
  summarise(median_cor = median(correlation_2 ), 
            min_cor = min(correlation_2), 
            max_cor = max(correlation_2), 
            length(correlation_2))


# Save Figure
# ggsave(corplot,
#        filename = fs::path(dir_figures,
#                            "correlation_plot_040926.jpeg"),
#        width = 12,
#        height = 10)

rm(cor_matrix, cor_matrix_df_1, cor_matrix_df_2, cor_matrix_df_3, cor_matrix_df_4,
   cor_method_df_1, cor_method_df_2, data_pfas_missing, pfas_mat_for_cor)
```

